EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_FGEM_fsPHENIX.C File Reference
G4_FGEM_fsPHENIX.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include "GlobalVariables.C"
Functions
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
void FGEM_Init ()
void FGEMSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.45)
void FGEM_FastSim_Reco (int verbosity=0)
void FGEM_FastSim_Eval (std::string outputfile, int verbosity=0)
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
1.2
Date
Date:
2014/01/22 01:44:13
Definition in file G4_FGEM_fsPHENIX.C.
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
Definition at line 179 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 179 of file G4_FGEM_fsPHENIX.C
References PHG4Sector::Sector_Geometry::AddLayer(), eic::cm, d, Acts::UnitConstants::e, PHG4SectorSubsystem::get_geometry(), eic::mm, Acts::UnitConstants::s, thickness, eic::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by FGEMSetup(), and make_GEM_station().
void FGEM_FastSim_Eval (std::string outputfile, int verbosity = 0)
Definition at line 359 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 359 of file G4_FGEM_fsPHENIX.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and PHG4TrackFastSimEval::set_filename().
Referenced by Fun4All_G4_fsPHENIX().
void FGEM_FastSim_Reco (int verbosity = 0)
Definition at line 253 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 253 of file G4_FGEM_fsPHENIX.C
References PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::add_state_name(), PHG4TrackFastSim::Cylinder, Acts::UnitConstants::e, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), Fun4AllBase::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.
Referenced by Fun4All_G4_fsPHENIX().
void FGEM_Init ()
Definition at line 29 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 29 of file G4_FGEM_fsPHENIX.C
References BlackHoleGeometry::max_radius.
Referenced by G4Init().
void FGEMSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.45)
Definition at line 37 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 37 of file G4_FGEM_fsPHENIX.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), cos(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), make_GEM_station(), name, overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup().
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8)
Definition at line 206 of file G4_FGEM_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 206 of file G4_FGEM_fsPHENIX.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by EGEMSetup(), and FGEMSetup().