EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_HcalOut_ref.C File Reference
G4_HcalOut_ref.C File Reference
#include "GlobalVariables.C"
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4detectors/PHG4OuterHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4HCALOUT
Enumerations
enum G4HCALOUT::enu_HCalOut_clusterizer { G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer }
Functions
void HCalOuterInit ()
double HCalOuter (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0, int verbosity=0)
void HCALOuter_Cells (int verbosity=0)
void HCALOuter_Towers (int verbosity=0)
void HCALOuter_Clusters (int verbosity=0)
void HCALOuter_Eval (std::string outputfile, int verbosity=0)
Variables
static bool Enable::HCALOUT = false
const double G4HCALOUT::outer_radius = 264.71
const double G4HCALOUT::size_z = 304.91 * 2
enu_HCalOut_clusterizer G4HCALOUT::HCalOut_clusterizer = kHCalOutTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Function Documentation
double HCalOuter (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0, int verbosity = 0)
Definition at line 55 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 55 of file G4_HcalOut_ref.C
References PHG4DetectorSubsystem::get_double_param(), hcal(), no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().
void HCALOuter_Cells (int verbosity = 0)
Definition at line 118 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 118 of file G4_HcalOut_ref.C
References PHG4HcalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void HCALOuter_Clusters (int verbosity = 0)
Definition at line 180 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 180 of file G4_HcalOut_ref.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), exit(), G4HCALOUT::HCalOut_clusterizer, Fun4AllServer::instance(), G4HCALOUT::kHCalOutGraphClusterizer, G4HCALOUT::kHCalOutTemplateClusterizer, Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::SetCylindricalGeometry(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void HCALOuter_Eval (std::string outputfile, int verbosity = 0)
Definition at line 210 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 210 of file G4_HcalOut_ref.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void HCALOuter_Towers (int verbosity = 0)
Definition at line 140 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 140 of file G4_HcalOut_ref.C
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void HCalOuterInit ()
Definition at line 48 of file G4_HcalOut_ref.C.
View newest version in sPHENIX GitHub at line 48 of file G4_HcalOut_ref.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, G4HCALOUT::outer_radius, and G4HCALOUT::size_z.
Referenced by G4Init().