EIC Software: ReadEICFiles Class Reference
ReadEICFiles Class Reference
#include <fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/ReadEICFiles.h>
Public Member Functions
ReadEICFiles (const std::string &name="EICReader")
virtual ~ReadEICFiles ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
bool OpenInputFile (const std::string &name)
void SetFirstEntry (int e)
void SetNodeName (const std::string &s)
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum EvtGen { Milou = 1, Unknown = 100 }
Private Member Functions
void GetTree ()
int CreateNodeTree (PHCompositeNode *topNode)
Private Attributes
std::string filename
TChain * Tin
int nEntries
int entry
int m_EvtGenId
erhic::EventMC * GenEvent
std::string _node_name
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 20 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 20 of file ReadEICFiles.h
Member Enumeration Documentation
enum ReadEICFiles::EvtGen private
Enumerator:
Milou
Unknown
Definition at line 79 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 79 of file ReadEICFiles.h
Constructor & Destructor Documentation
ReadEICFiles::ReadEICFiles (const std::string & name = "EICReader")
Definition at line 46 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 46 of file ReadEICFiles.cc
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
ReadEICFiles::~ReadEICFiles () virtual
Definition at line 62 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 62 of file ReadEICFiles.cc
References Tin.
Member Function Documentation
int ReadEICFiles::CreateNodeTree (PHCompositeNode * topNode) private
Creade node on node tree
Definition at line 351 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 351 of file ReadEICFiles.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), PHHepMCGenHelper::create_node_tree(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), hepmc_helper, and PHWHERE.
Referenced by Init().
int ReadEICFiles::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 64 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 64 of file ReadEICFiles.h
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
void ReadEICFiles::GetTree () private
Get tree from input file
Definition at line 80 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 80 of file ReadEICFiles.cc
References GenEvent, m_EvtGenId, nEntries, Tin, and Fun4AllBase::Verbosity().
Referenced by OpenInputFile().
int ReadEICFiles::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 98 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 98 of file ReadEICFiles.cc
References CreateNodeTree().
bool ReadEICFiles::OpenInputFile (const std::string & name)
Specify name of input file to open
Definition at line 69 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 69 of file ReadEICFiles.cc
References filename, GetTree(), name, and Tin.
Referenced by Fun4All_EIC_Generator_Display(), Fun4All_G4_EICDetector(), and Fun4All_Generator_Display().
int ReadEICFiles::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 105 of file ReadEICFiles.cc.
View newest version in sPHENIX GitHub at line 105 of file ReadEICFiles.cc
References Fun4AllReturnCodes::ABORTRUN, entry, filename, GenEvent, erhic::ParticleMCbase::GetE(), erhic::ParticleMCbase::GetIndex(), erhic::ParticleMCbase::GetM(), erhic::EventMC::GetNTracks(), erhic::ParticleMCbase::GetParentIndex(), erhic::EventMC::GetProcess(), erhic::ParticleMCbase::GetPx(), erhic::ParticleMCbase::GetPy(), erhic::ParticleMCbase::GetPz(), erhic::EventDis::GetQ2(), erhic::ParticleMCbase::GetStatus(), erhic::EventMC::GetTrack(), erhic::ParticleMCbase::GetVertex(), erhic::EventDis::GetX(), hepmc_helper, erhic::ParticleMCbase::Id(), PHHepMCGenHelper::insert_event(), eic::m, m_EvtGenId, nEntries, PHHepMCGenEvent::print(), EicEventHeader::set_eventgenerator_type(), EicEventHeader::set_milou_trueQ2(), EicEventHeader::set_milou_trueX(), EicEventHeader::set_milou_weight(), Tin, erhic::EventMilou::trueQ2, erhic::EventMilou::trueX, v, Fun4AllBase::Verbosity(), and erhic::EventMilou::weight.
void ReadEICFiles::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 70 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 70 of file ReadEICFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
void ReadEICFiles::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 55 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 55 of file ReadEICFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
void ReadEICFiles::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 37 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 37 of file ReadEICFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void ReadEICFiles::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 43 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 43 of file ReadEICFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
void ReadEICFiles::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 49 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 49 of file ReadEICFiles.h
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
void ReadEICFiles::SetFirstEntry (int e) inline
Set first entry from input tree to be used
Definition at line 33 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 33 of file ReadEICFiles.h
References Acts::UnitConstants::e, and entry.
void ReadEICFiles::SetNodeName (const std::string & s) inline
Set name of output node
Definition at line 35 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 35 of file ReadEICFiles.h
References _node_name, and Acts::UnitConstants::s.
Member Data Documentation
std::string ReadEICFiles::_node_name private
Definition at line 106 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 106 of file ReadEICFiles.h
Referenced by SetNodeName().
int ReadEICFiles::entry private
Number of current event being used from input tree
Definition at line 95 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 95 of file ReadEICFiles.h
Referenced by process_event(), and SetFirstEntry().
std::string ReadEICFiles::filename private
Name of file containing input tree
Definition at line 86 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 86 of file ReadEICFiles.h
Referenced by OpenInputFile(), and process_event().
erhic::EventMC* ReadEICFiles::GenEvent private
Pinter to event record in tree (= branch). Use 'abstract' EventMC class pointer from which all event types (erhic::EventMilou etc) inherit from.
Definition at line 103 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 103 of file ReadEICFiles.h
Referenced by GetTree(), and process_event().
PHHepMCGenHelper ReadEICFiles::hepmc_helper private
helper for insert HepMC event to DST node and add vertex smearing
Definition at line 109 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 109 of file ReadEICFiles.h
Referenced by CreateNodeTree(), get_embedding_id(), process_event(), ReadEICFiles(), set_embedding_id(), set_reuse_vertex(), set_vertex_distribution_function(), set_vertex_distribution_mean(), and set_vertex_distribution_width().
int ReadEICFiles::m_EvtGenId private
Event Generator id
Definition at line 98 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 98 of file ReadEICFiles.h
Referenced by GetTree(), and process_event().
int ReadEICFiles::nEntries private
Number of events in input tree
Definition at line 92 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 92 of file ReadEICFiles.h
Referenced by GetTree(), and process_event().
TChain* ReadEICFiles::Tin private
Input tree created with eic-smear tree builder
Definition at line 89 of file ReadEICFiles.h.
View newest version in sPHENIX GitHub at line 89 of file ReadEICFiles.h
Referenced by GetTree(), OpenInputFile(), process_event(), and ~ReadEICFiles().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/ReadEICFiles.h
fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/ReadEICFiles.cc