EIC Software: ActsCovarianceRotater Class Reference
ActsCovarianceRotater Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/ActsCovarianceRotater.h>
Public Member Functions
ActsCovarianceRotater ()
virtual ~ActsCovarianceRotater ()
Acts::BoundSymMatrix rotateSvtxTrackCovToActs (const SvtxTrack *track)
Acts::BoundSymMatrix rotateActsCovToSvtxTrack (const Acts::KalmanFitterResult< SourceLink > &fitOutput)
Same as above, but rotate from Acts basis to global (x,y,z,px,py,pz)
void setVerbosity (bool verbosity)
void printMatrix (const std::string message, Acts::BoundSymMatrix matrix)
Private Attributes
bool m_verbosity
Detailed Description
This is a helper class for rotating track covariance matrices to and from the basis that Acts expects. The covariance matrix is nominally given in the global basis (x,y,z,px,py,pz). Acts expects the covariance matrix in a local basis with respect to the given reference point that is provided as an option to the KalmanFitter.
Definition at line 30 of file ActsCovarianceRotater.h.
View newest version in sPHENIX GitHub at line 30 of file ActsCovarianceRotater.h
Constructor & Destructor Documentation
ActsCovarianceRotater::ActsCovarianceRotater () inline
Definition at line 33 of file ActsCovarianceRotater.h.
View newest version in sPHENIX GitHub at line 33 of file ActsCovarianceRotater.h
virtual ActsCovarianceRotater::~ActsCovarianceRotater () inline virtual
Definition at line 36 of file ActsCovarianceRotater.h.
View newest version in sPHENIX GitHub at line 36 of file ActsCovarianceRotater.h
Member Function Documentation
void ActsCovarianceRotater::printMatrix (const std::string message, Acts::BoundSymMatrix matrix)
Definition at line 181 of file ActsCovarianceRotater.cc.
View newest version in sPHENIX GitHub at line 181 of file ActsCovarianceRotater.cc
References m_verbosity, and matrix().
Referenced by rotateActsCovToSvtxTrack(), and rotateSvtxTrackCovToActs().
Acts::BoundSymMatrix ActsCovarianceRotater::rotateActsCovToSvtxTrack (const Acts::KalmanFitterResult< SourceLink > & fitOutput)
Same as above, but rotate from Acts basis to global (x,y,z,px,py,pz)
This is the original matrix we rotated by. So instead of rotating as normal RCR^T, we will just rotate back by rotating by the same matrix as R^TCR Position rotation to Acts loc0 and loc1, which are the local points on a surface centered at the (x,y,z) global position with normal vector in the direction of the unit momentum vector
q/p rotaton
convert back to sPHENIX coordinates of cm
Definition at line 92 of file ActsCovarianceRotater.cc.
View newest version in sPHENIX GitHub at line 92 of file ActsCovarianceRotater.cc
References charge, Acts::UnitConstants::cm, Acts::UnitConstants::cm2, Acts::KalmanFitterResult< source_link_t >::fittedParameters, printMatrix(), r, x, y, and z.
Referenced by PHActsTrkFitter::updateSvtxTrack().
Acts::BoundSymMatrix ActsCovarianceRotater::rotateSvtxTrackCovToActs (const SvtxTrack * track)
Rotates an SvtxTrack covariance matrix from (x,y,z,px,py,pz) global cartesian coordinates to (d0, z0, phi, theta, q/p, time) coordinates for Acts. The track fitter performs the fitting with respect to the nominal origin of sPHENIX, so we rotate accordingly
Convert Svtx to mm and GeV units as Acts expects
Position rotation to Acts loc0 and loc1, which are the local points on a surface centered at the (x,y,z) global position with normal vector in the direction of the unit momentum vector
q/p rotaton
time is left as 0
Definition at line 4 of file ActsCovarianceRotater.cc.
View newest version in sPHENIX GitHub at line 4 of file ActsCovarianceRotater.cc
References charge, Acts::UnitConstants::cm, Acts::UnitConstants::cm2, SvtxTrack::get_charge(), SvtxTrack::get_error(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), matrix(), printMatrix(), r, x, y, and z.
Referenced by PHActsTrkProp::Process(), and PHActsTracks::process_event().
void ActsCovarianceRotater::setVerbosity (bool verbosity) inline
Definition at line 48 of file ActsCovarianceRotater.h.
View newest version in sPHENIX GitHub at line 48 of file ActsCovarianceRotater.h
References m_verbosity.
Member Data Documentation
bool ActsCovarianceRotater::m_verbosity private
Definition at line 53 of file ActsCovarianceRotater.h.
View newest version in sPHENIX GitHub at line 53 of file ActsCovarianceRotater.h
Referenced by printMatrix(), and setVerbosity().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/ActsCovarianceRotater.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/ActsCovarianceRotater.cc