EIC Software: eic-smear/blob/master/tests/particlegun.cxx File Reference
particlegun.cxx File Reference
#include <iomanip>
#include <TDatabasePDG.h>
#include <TH1.h>
#include <TH2.h>
#include <TCanvas.h>
#include <TLegend.h>
#include <TStyle.h>
#include "ePHENIXDetector.h"
#include "eicsmear/smear/Detector.h"
Classes
struct EicSmearStep
struct EicSmearStatistics
Enumerations
enum EicSmearResults {
null_particle, zero_e_smear_p, smear_e_zero_p, smear_e_smear_p,
zero_e_zero_p
}
Functions
Smear::Detector BuildZeus ()
Smear::Detector BuildBeAST ()
Smear::Detector BuildHandBookDetector ()
Smear::Detector BuildPerfectDetector ()
EicSmearStep DoSmearStep (int pdg, TLorentzVector &input_vect, Smear::Detector &detector)
This function does smearing itself. by calling detector.Smear(not_smeared_prt);.
EicSmearStatistics Process (int pdg, Smear::Detector &detector)
void PrintSmearStats (const EicSmearStatistics &stat)
int main ()
Variables
const double deg_to_rad = 0.01745329251
Enumeration Type Documentation
enum EicSmearResults
Enumerator:
null_particle
zero_e_smear_p
smear_e_zero_p
smear_e_smear_p
zero_e_zero_p
Definition at line 22 of file particlegun.cxx.
View newest version in sPHENIX GitHub at line 22 of file particlegun.cxx
Function Documentation
Smear::Detector BuildBeAST ()
Definition at line 12 of file smearBeAST.cxx.
View newest version in sPHENIX GitHub at line 12 of file smearBeAST.cxx
Smear::Detector BuildHandBookDetector ()
Definition at line 42 of file smearHandBook.cxx.
View newest version in sPHENIX GitHub at line 42 of file smearHandBook.cxx
Smear::Detector BuildPerfectDetector ()
Definition at line 30 of file PerfectDetector.cxx.
View newest version in sPHENIX GitHub at line 30 of file PerfectDetector.cxx
Smear::Detector BuildZeus ()
Smearing parameterisations for the ZEUS detector.
See JHEP05 (2009) 108.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script.
Definition at line 45 of file ZEUSDetector.cpp.
View newest version in sPHENIX GitHub at line 45 of file ZEUSDetector.cpp
EicSmearStep DoSmearStep (int pdg, TLorentzVector & input_vect, Smear::Detector & detector)
This function does smearing itself. by calling detector.Smear(not_smeared_prt);.
Definition at line 57 of file particlegun.cxx.
View newest version in sPHENIX GitHub at line 57 of file particlegun.cxx
References Smear::ParticleMCS::Get4Vector(), Smear::ParticleMCS::GetE(), Smear::ParticleMCS::GetP(), EicSmearStep::not_smeared_lorentz, null_particle, EicSmearStep::result, erhic::ParticleMCbase::Set4Vector(), erhic::ParticleMCbase::SetId(), erhic::ParticleMCbase::SetIndex(), erhic::ParticleMCbase::SetStatus(), Smear::Detector::Smear(), smear_e_smear_p, smear_e_zero_p, EicSmearStep::smeared_lorentz, Acts::Test::step(), zero_e_smear_p, and zero_e_zero_p.
Referenced by Process().
int main (void)
Definition at line 196 of file particlegun.cxx.
View newest version in sPHENIX GitHub at line 196 of file particlegun.cxx
References BuildBeAST(), BuildEphoenix(), BuildHandBookDetector(), BuildPerfectDetector(), BuildZeus(), leg(), max, EicSmearStatistics::null_particles_eta, pid, PrintSmearStats(), Process(), EicSmearStatistics::smear_DelP, EicSmearStatistics::smear_e_smear_p_eta, EicSmearStatistics::smear_e_zero_p_eta, title(), ymax, and EicSmearStatistics::zero_e_smear_p_eta.
void PrintSmearStats (const EicSmearStatistics & stat)
Definition at line 183 of file particlegun.cxx.
View newest version in sPHENIX GitHub at line 183 of file particlegun.cxx
References EicSmearStatistics::null_particles, EicSmearStatistics::smear_e_smear_p, EicSmearStatistics::smear_e_zero_p, EicSmearStatistics::total_particles, EicSmearStatistics::zero_e_smear_p, and EicSmearStatistics::zero_e_zero_p.
Referenced by main().
EicSmearStatistics Process (int pdg, Smear::Detector & detector)
Definition at line 116 of file particlegun.cxx.
View newest version in sPHENIX GitHub at line 116 of file particlegun.cxx
References Acts::Test::db, deg_to_rad, DoSmearStep(), null_particle, EicSmearStep::result, smear_e_smear_p, smear_e_zero_p, EicSmearStep::smeared_lorentz, Acts::Test::step(), EicSmearStatistics::total_particles, zero_e_smear_p, and zero_e_zero_p.
Referenced by main().
Variable Documentation
const double deg_to_rad = 0.01745329251
Definition at line 18 of file particlegun.cxx.
View newest version in sPHENIX GitHub at line 18 of file particlegun.cxx
Referenced by Process().