EIC Software: PHActsTrkFitter Class Reference
PHActsTrkFitter Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkFitter.h>
Public Member Functions
PHActsTrkFitter (const std::string &name="PHActsTrkFitter")
Default constructor.
~PHActsTrkFitter ()
Destructor.
int End (PHCompositeNode *)
End, write and close files.
int Setup (PHCompositeNode *topNode)
Get and create nodes.
int Process ()
Process each event by calling the fitter.
void setTimeAnalysis (bool time)
Public Member Functions inherited from PHTrackFitting
PHTrackFitting (const std::string &name="PHTrackFitting")
virtual ~PHTrackFitting ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *)
Get all the nodes.
int createNodes (PHCompositeNode *)
Create new nodes.
void updateSvtxTrack (const Acts::KalmanFitterResult< SourceLink > &fitOutput, const unsigned int trackKey)
Convert the acts track fit result to an svtx track.
Private Attributes
int m_event
Event counter.
std::map< unsigned int,
ActsTrack > * m_actsProtoTracks
Map of acts tracks and track key created by PHActsTracks.
ActsTrackingGeometry * m_tGeometry
Options that Acts::Fitter needs to run from MakeActsGeometry.
FW::TrkrClusterFittingAlgorithm::Config fitCfg
Configuration containing the fitting function instance.
SvtxTrackMap * m_trackMap
TrackMap containing SvtxTracks.
int m_nBadFits
bool m_timeAnalysis
Variables for doing event time execution analysis.
TFile * m_timeFile
TH1 * h_eventTime
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Attributes inherited from PHTrackFitting
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
Detailed Description
Definition at line 44 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 44 of file PHActsTrkFitter.h
Constructor & Destructor Documentation
PHActsTrkFitter::PHActsTrkFitter (const std::string & name = "PHActsTrkFitter")
Default constructor.
Definition at line 36 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 36 of file PHActsTrkFitter.cc
References Fun4AllBase::Verbosity().
PHActsTrkFitter::~PHActsTrkFitter ()
Destructor.
Definition at line 51 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 51 of file PHActsTrkFitter.cc
Member Function Documentation
int PHActsTrkFitter::createNodes (PHCompositeNode * topNode) private
Create new nodes.
Definition at line 230 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 230 of file PHActsTrkFitter.cc
References Fun4AllReturnCodes::EVENT_OK.
int PHActsTrkFitter::End (PHCompositeNode * topNode) virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 174 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 174 of file PHActsTrkFitter.cc
References Fun4AllReturnCodes::EVENT_OK, h_eventTime, m_nBadFits, m_timeAnalysis, m_timeFile, and Fun4AllBase::Verbosity().
int PHActsTrkFitter::getNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 235 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 235 of file PHActsTrkFitter.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_actsProtoTracks, m_tGeometry, m_trackMap, and PHWHERE.
Referenced by Setup().
int PHActsTrkFitter::Process () virtual
Process each event by calling the fitter.
Construct a perigee surface as the target surface This surface is what Acts fits with respect to. So we put it at 0 so that the fitter is fitting with respect to the global position. Presumably we could put this as the zvertex
Can correlate with the SvtxTrackMap with the key
Call KF now. Have a vector of sourceLinks corresponding to clusters associated to this track and the corresponding track seed which corresponds to the PHGenFitTrkProp track seeds
Check that the track fit result did not return an error
Get position, momentum from the Acts output. Update the values of the proto track
Mark the SvtxTrack as bad, for better analysis can remove later
Implements PHTrackFitting.
Definition at line 73 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 73 of file PHActsTrkFitter.cc
References ActsTrackingGeometry::calibContext, Fun4AllReturnCodes::EVENT_OK, SvtxTrackMap::find(), fitCfg, Acts::KalmanFitterResult< source_link_t >::fittedParameters, ActsTrackingGeometry::geoContext, ActsTrack::getSourceLinks(), ActsTrack::getTrackParams(), h_eventTime, m_actsProtoTracks, m_event, m_nBadFits, m_tGeometry, m_timeAnalysis, m_trackMap, ActsTrackingGeometry::magFieldContext, Acts::SingleTrackParameters< ChargePolicy >::momentum(), PHWHERE, Acts::SingleTrackParameters< ChargePolicy >::position(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrack::set_x(), SvtxTrack::set_y(), SvtxTrack::set_z(), updateSvtxTrack(), and Fun4AllBase::Verbosity().
void PHActsTrkFitter::setTimeAnalysis (bool time) inline
Definition at line 62 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 62 of file PHActsTrkFitter.h
References m_timeAnalysis, and Acts::VectorHelpers::time().
int PHActsTrkFitter::Setup (PHCompositeNode * topNode) virtual
Get and create nodes.
Reimplemented from PHTrackFitting.
Definition at line 55 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 55 of file PHActsTrkFitter.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, fitCfg, getNodes(), h_eventTime, Acts::Logging::INFO, m_tGeometry, m_timeAnalysis, m_timeFile, ActsTrackingGeometry::magField, and ActsTrackingGeometry::tGeometry.
void PHActsTrkFitter::updateSvtxTrack (const Acts::KalmanFitterResult< SourceLink > & fitOutput, const unsigned int trackKey) private
Convert the acts track fit result to an svtx track.
Acts default unit is mm. So convert to cm
This will contain the chi2/ndf
Definition at line 193 of file PHActsTrkFitter.cc.
View newest version in sPHENIX GitHub at line 193 of file PHActsTrkFitter.cc
References Acts::UnitConstants::cm, SvtxTrackMap::find(), Acts::KalmanFitterResult< source_link_t >::fittedParameters, Acts::KalmanFitterResult< source_link_t >::fittedStates, m_trackMap, ActsCovarianceRotater::rotateActsCovToSvtxTrack(), SvtxTrack::set_error(), SvtxTrack::set_px(), SvtxTrack::set_py(), SvtxTrack::set_pz(), SvtxTrack::set_x(), SvtxTrack::set_y(), and SvtxTrack::set_z().
Referenced by Process().
Member Data Documentation
FW::TrkrClusterFittingAlgorithm::Config PHActsTrkFitter::fitCfg private
Configuration containing the fitting function instance.
Definition at line 84 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 84 of file PHActsTrkFitter.h
Referenced by Process(), and Setup().
TH1* PHActsTrkFitter::h_eventTime private
Definition at line 94 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 94 of file PHActsTrkFitter.h
Referenced by End(), Process(), and Setup().
std::map<unsigned int, ActsTrack>* PHActsTrkFitter::m_actsProtoTracks private
Map of acts tracks and track key created by PHActsTracks.
Definition at line 78 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 78 of file PHActsTrkFitter.h
Referenced by getNodes(), and Process().
int PHActsTrkFitter::m_event private
Event counter.
Definition at line 66 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 66 of file PHActsTrkFitter.h
Referenced by Process().
int PHActsTrkFitter::m_nBadFits private
Definition at line 89 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 89 of file PHActsTrkFitter.h
Referenced by End(), and Process().
ActsTrackingGeometry* PHActsTrkFitter::m_tGeometry private
Options that Acts::Fitter needs to run from MakeActsGeometry.
Definition at line 81 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 81 of file PHActsTrkFitter.h
Referenced by getNodes(), Process(), and Setup().
bool PHActsTrkFitter::m_timeAnalysis private
Variables for doing event time execution analysis.
Definition at line 92 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 92 of file PHActsTrkFitter.h
Referenced by End(), Process(), setTimeAnalysis(), and Setup().
TFile* PHActsTrkFitter::m_timeFile private
Definition at line 93 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 93 of file PHActsTrkFitter.h
Referenced by End(), and Setup().
SvtxTrackMap* PHActsTrkFitter::m_trackMap private
TrackMap containing SvtxTracks.
Definition at line 87 of file PHActsTrkFitter.h.
View newest version in sPHENIX GitHub at line 87 of file PHActsTrkFitter.h
Referenced by getNodes(), Process(), and updateSvtxTrack().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkFitter.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkFitter.cc