EIC Software: PHActsTrkProp Class Reference
PHActsTrkProp Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkProp.h>
Public Member Functions
PHActsTrkProp (const std::string &name="PHActsTrkProp")
Default constructor.
~PHActsTrkProp ()
Destructor.
int End ()
End, write and close files.
int Setup (PHCompositeNode *topNode)
Get and create nodes.
int Process ()
Process each event by calling the fitter.
Public Member Functions inherited from PHTrackPropagating
PHTrackPropagating (const std::string &name="PHTrackPropagating")
virtual ~PHTrackPropagating ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int getNodes (PHCompositeNode *topNode)
Get all the nodes.
void createNodes (PHCompositeNode *topNode)
Create new nodes.
Private Attributes
int m_event
Event counter.
ActsTrackingGeometry * m_tGeometry
SvtxTrackMap * m_trackMap
Track map with Svtx objects.
std::vector< ActsTrack > * m_actsProtoTracks
Acts proto tracks to be put on the node tree by this module.
std::map< TrkrDefs::cluskey,
unsigned int > * m_hitIdClusKey
Map of cluster keys to hit ids, for debugging statements.
std::map< unsigned int,
SourceLink > * m_sourceLinks
SourceLinkSelectorConfig m_sourceLinkSelectorConfig
FW::TrkrClusterFindingAlgorithm::Config findCfg
Configuration containing the finding function instance.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Attributes inherited from PHTrackPropagating
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
Detailed Description
Definition at line 51 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 51 of file PHActsTrkProp.h
Constructor & Destructor Documentation
PHActsTrkProp::PHActsTrkProp (const std::string & name = "PHActsTrkProp")
Default constructor.
Fun4All includes.
Tracking includes
Definition at line 50 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 50 of file PHActsTrkProp.cc
References Fun4AllBase::Verbosity().
PHActsTrkProp::~PHActsTrkProp ()
Destructor.
Definition at line 62 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 62 of file PHActsTrkProp.cc
Member Function Documentation
void PHActsTrkProp::createNodes (PHCompositeNode * topNode) private
Create new nodes.
Definition at line 229 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 229 of file PHActsTrkProp.cc
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and m_actsProtoTracks.
Referenced by Setup().
int PHActsTrkProp::End () virtual
End, write and close files.
Implements PHTrackPropagating.
Definition at line 220 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 220 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
int PHActsTrkProp::getNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 267 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 267 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, m_hitIdClusKey, m_sourceLinks, m_tGeometry, m_trackMap, and PHWHERE.
Referenced by Setup().
int PHActsTrkProp::Process () virtual
Process each event by calling the fitter.
Collect all source links for the CKF
Get the necessary parameters and values for the TrackParameters
Construct the options to pass to the CKF. SourceLinkSelector set in Init()
Run the CKF for all source links and the constructed track seed
how to get the associated source links from fit result?
Get the finder results into a FW::TrackParameters
Implements PHTrackPropagating.
Definition at line 94 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 94 of file PHActsTrkProp.cc
References SvtxTrackMap::begin(), ActsTrackingGeometry::calibContext, SvtxTrackMap::end(), Fun4AllReturnCodes::EVENT_OK, findCfg, ActsTrackingGeometry::geoContext, SvtxTrack::get_charge(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), SvtxTrack::identify(), m_actsProtoTracks, m_event, m_sourceLinks, m_sourceLinkSelectorConfig, m_tGeometry, m_trackMap, ActsTrackingGeometry::magFieldContext, Acts::UnitConstants::ns, PHWHERE, ActsCovarianceRotater::rotateSvtxTrackCovToActs(), and Fun4AllBase::Verbosity().
int PHActsTrkProp::Setup (PHCompositeNode * topNode) virtual
Get and create nodes.
Need to implement different chi2 criteria for the different layers and volumes to help the CKF out a little First need to walk through layers/volumes to figure out appropriate numerical identifiers Leave these out for now once we return to track propagation m_sourceLinkSelectorConfig.layerMaxChi2 = {{2, {{2, 8}, {4, 7}}}}; m_sourceLinkSelectorConfig.volumeMaxChi2 = {{2, 7}, {3, 8}}; m_sourceLinkSelectorConfig.maxChi2 = 8; Set the allowed maximum number of source links to be large enough m_sourceLinkSelectorConfig.maxNumSourcelinksOnSurface = 100;
Reimplemented from PHTrackPropagating.
Definition at line 66 of file PHActsTrkProp.cc.
View newest version in sPHENIX GitHub at line 66 of file PHActsTrkProp.cc
References Fun4AllReturnCodes::ABORTEVENT, createNodes(), Fun4AllReturnCodes::EVENT_OK, findCfg, getNodes(), m_tGeometry, ActsTrackingGeometry::magField, ActsTrackingGeometry::tGeometry, and Acts::Logging::VERBOSE.
Member Data Documentation
FW::TrkrClusterFindingAlgorithm::Config PHActsTrkProp::findCfg private
Configuration containing the finding function instance.
Definition at line 99 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 99 of file PHActsTrkProp.h
Referenced by Process(), and Setup().
std::vector<ActsTrack>* PHActsTrkProp::m_actsProtoTracks private
Acts proto tracks to be put on the node tree by this module.
Definition at line 85 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 85 of file PHActsTrkProp.h
Referenced by createNodes(), and Process().
int PHActsTrkProp::m_event private
Event counter.
Definition at line 71 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 71 of file PHActsTrkProp.h
Referenced by Process().
std::map<TrkrDefs::cluskey, unsigned int>* PHActsTrkProp::m_hitIdClusKey private
Map of cluster keys to hit ids, for debugging statements.
Definition at line 88 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 88 of file PHActsTrkProp.h
Referenced by getNodes().
std::map<unsigned int, SourceLink>* PHActsTrkProp::m_sourceLinks private
Acts source links created by PHActsSourceLinks SourceLink is defined as TrkrClusterSourceLink elsewhere
Definition at line 92 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 92 of file PHActsTrkProp.h
Referenced by getNodes(), and Process().
SourceLinkSelectorConfig PHActsTrkProp::m_sourceLinkSelectorConfig private
SourceLinkSelector to help the CKF identify which source links may belong to a track seed based on geometry considerations
Definition at line 96 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 96 of file PHActsTrkProp.h
Referenced by Process().
ActsTrackingGeometry* PHActsTrkProp::m_tGeometry private
Definition at line 79 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 79 of file PHActsTrkProp.h
Referenced by getNodes(), Process(), and Setup().
SvtxTrackMap* PHActsTrkProp::m_trackMap private
Track map with Svtx objects.
Definition at line 82 of file PHActsTrkProp.h.
View newest version in sPHENIX GitHub at line 82 of file PHActsTrkProp.h
Referenced by getNodes(), and Process().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkProp.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/PHActsTrkProp.cc