EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_FEMC_EIC.C File Reference
G4_FEMC_EIC.C File Reference
#include "GlobalVariables.C"
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4ForwardCalCellReco.h>
#include <g4detectors/PHG4ForwardEcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4FEMC
Enumerations
enum G4FEMC::enu_Femc_clusterizer { G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer }
Functions
void FEMCInit ()
void FEMC_Cells (int verbosity=0)
void FEMCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void FEMC_Towers (int verbosity=0)
void FEMC_Clusters (int verbosity=0)
void FEMC_Eval (std::string outputfile, int verbosity=0)
Variables
static bool Enable::FEMC = false
const double G4FEMC::Gz0 = 310.
const double G4FEMC::Gdz = 36.5
const double G4FEMC::outer_radius = 182.655
enu_Femc_clusterizer G4FEMC::Femc_clusterizer = kFemcTemplateClusterizer
Function Documentation
void FEMC_Cells (int verbosity = 0)
Definition at line 49 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 49 of file G4_FEMC_EIC.C
References PHG4ForwardCalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
void FEMC_Clusters (int verbosity = 0)
Definition at line 208 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 208 of file G4_FEMC_EIC.C
References RawClusterBuilderTemplate::Detector(), RawClusterBuilderFwd::Detector(), exit(), G4FEMC::Femc_clusterizer, Fun4AllServer::instance(), G4FEMC::kFemcGraphClusterizer, G4FEMC::kFemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), RawClusterBuilderTemplate::set_threshold_energy(), and Fun4AllBase::Verbosity().
void FEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 241 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 241 of file G4_FEMC_EIC.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
void FEMC_Towers (int verbosity = 0)
Definition at line 86 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 86 of file G4_FEMC_EIC.C
References RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::TowerType(), RawTowerCalibration::TowerType(), and Fun4AllBase::Verbosity().
void FEMCInit ()
Definition at line 43 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 43 of file G4_FEMC_EIC.C
References G4FEMC::Gdz, G4FEMC::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, and G4FEMC::outer_radius.
void FEMCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated FEMC module
Definition at line 60 of file G4_FEMC_EIC.C.
View newest version in sPHENIX GitHub at line 60 of file G4_FEMC_EIC.C
References femc(), Fun4AllServer::instance(), overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4ForwardEcalSubsystem::SetTowerMappingFile(), and PHG4DetectorSubsystem::SuperDetector().