EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C File Reference
G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C File Reference
#include "GlobalVariables.C"
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4mvtx/PHG4MvtxDefs.h>
#include <g4mvtx/PHG4MvtxSubsystem.h>
#include <g4tpc/PHG4TpcSpaceChargeDistortion.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
#include <vector>
Namespaces
namespace TrackingEicMvtxMacro
namespace TrackingEicTpcMacro
Enumerations
enum TPC_Gas {
Ne2K_100, Ne2K_400, NeCF4_100, NeCF4_300,
NeCF4_400, ByHand
}
Functions
void SvtxInit (int verbosity=0)
double Svtx (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Svtx_Cells (int verbosity=0)
void Svtx_Reco (int verbosity=0)
Variables
const int TrackingEicMvtxMacro::n_maps_layer = 3
int TrackingEicTpcMacro::n_tpc_layer_inner = 16
double TrackingEicTpcMacro::tpc_layer_thick_inner = 1.25
int TrackingEicTpcMacro::tpc_layer_rphi_count_inner = 1152
int TrackingEicTpcMacro::n_tpc_layer_mid = 16
double TrackingEicTpcMacro::tpc_layer_thick_mid = 1.25
int TrackingEicTpcMacro::tpc_layer_rphi_count_mid = 1536
int TrackingEicTpcMacro::n_tpc_layer_outer = 16
double TrackingEicTpcMacro::tpc_layer_thick_outer = 1.125
int TrackingEicTpcMacro::tpc_layer_rphi_count_outer = 2304
double inner_cage_radius = 20.
TPC_Gas ether = TPC_Gas::NeCF4_400
double Ne_dEdx = 1.56
double CF4_dEdx = 7.00
double iBut_dEdx = 5.93
double Ne_NPrimary = 12
double CF4_NPrimary = 51
double iBut_NPrimary = 84
double Ne_NTotal = 43
double CF4_NTotal = 100
double iBut_NTotal = 195
double TPC_SigmaT = 0.03
double TPCDriftVelocity
double TPC_Trans_Diffusion
double TPC_Long_Diffusion
double TPC_dEdx
double TPC_NPri
double TPC_NTot
double TPC_ElectronsPerKeV
double TPCADCClock
double TPCShapingRMSLead
double TPCShapingRMSTail
double tpc_cell_z
double TPC_SmearRPhi
double TPC_SmearZ
Enumeration Type Documentation
enum TPC_Gas
Enumerator:
Ne2K_100
Ne2K_400
NeCF4_100
NeCF4_300
NeCF4_400
ByHand
Definition at line 53 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 53 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Function Documentation
double Svtx (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 213 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 213 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
References G4TPC::cage_length, G4TPC::cage_thickness, PHG4MvtxDefs::GLOBAL, inner_cage_radius, M_PI, n_gas_layer, TrackingEicMvtxMacro::n_maps_layer, G4TPC::n_rad_length_cage, MVTX::N_staves, TrackingEicTpcMacro::n_tpc_layer_inner, TrackingEicTpcMacro::n_tpc_layer_mid, TrackingEicTpcMacro::n_tpc_layer_outer, MVTX::nom_radius, G4FEMC::outer_radius, PHG4DetectorGroupSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorGroupSubsystem::set_double_param(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorGroupSubsystem::set_int_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorGroupSubsystem::set_string_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorGroupSubsystem::SetActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), G4TPC::tpcgas, and Fun4AllBase::Verbosity().
void Svtx_Cells (int verbosity = 0)
Definition at line 328 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 328 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
References Fun4AllServer::instance().
void Svtx_Reco (int verbosity = 0)
Definition at line 354 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 354 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
References Fun4AllServer::instance().
void SvtxInit (int verbosity = 0)
Definition at line 104 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 104 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
References ByHand, CF4_dEdx, CF4_NPrimary, CF4_NTotal, ether, iBut_dEdx, iBut_NPrimary, iBut_NTotal, Ne2K_100, Ne2K_400, Ne_dEdx, Ne_NPrimary, Ne_NTotal, NeCF4_100, NeCF4_300, NeCF4_400, tpc_cell_z, TPC_dEdx, TPC_ElectronsPerKeV, TPC_Long_Diffusion, TPC_NPri, TPC_NTot, TPC_SmearRPhi, TPC_SmearZ, TPC_Trans_Diffusion, TPCADCClock, TPCDriftVelocity, TPCShapingRMSLead, and TPCShapingRMSTail.
Variable Documentation
double CF4_dEdx = 7.00
Definition at line 68 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 68 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by PHG4TpcElectronDrift::SetDefaultParameters(), and SvtxInit().
double CF4_NPrimary = 51
Definition at line 72 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 72 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double CF4_NTotal = 100
Definition at line 76 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 76 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by PHG4TpcElectronDrift::SetDefaultParameters(), and SvtxInit().
TPC_Gas ether = TPC_Gas::NeCF4_400
Definition at line 62 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 62 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double iBut_dEdx = 5.93
Definition at line 69 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 69 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double iBut_NPrimary = 84
Definition at line 73 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 73 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double iBut_NTotal = 195
Definition at line 77 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 77 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double inner_cage_radius = 20.
Definition at line 47 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 47 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by Svtx().
double Ne_dEdx = 1.56
Definition at line 67 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 67 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by PHG4TpcElectronDrift::SetDefaultParameters(), and SvtxInit().
double Ne_NPrimary = 12
Definition at line 71 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 71 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double Ne_NTotal = 43
Definition at line 75 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 75 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by PHG4TpcElectronDrift::SetDefaultParameters(), and SvtxInit().
double tpc_cell_z
Definition at line 98 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 98 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_dEdx
Definition at line 86 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 86 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_ElectronsPerKeV
Definition at line 89 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 89 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_Long_Diffusion
Definition at line 85 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 85 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_NPri
Definition at line 87 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 87 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_NTot
Definition at line 88 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 88 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_SigmaT = 0.03
Definition at line 80 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 80 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
double TPC_SmearRPhi
Definition at line 99 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 99 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_SmearZ
Definition at line 100 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 100 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPC_Trans_Diffusion
Definition at line 84 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 84 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPCADCClock
Definition at line 95 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 95 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPCDriftVelocity
Definition at line 83 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 83 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPCShapingRMSLead
Definition at line 96 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 96 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().
double TPCShapingRMSTail
Definition at line 97 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C.
View newest version in sPHENIX GitHub at line 97 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C
Referenced by SvtxInit().