EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4Setup_fsPHENIX.C File Reference
G4Setup_fsPHENIX.C File Reference
#include "GlobalVariables.C"
#include "G4_Pipe.C"
#include "G4_Tracking.C"
#include "G4_CEmc_Spacal.C"
#include "G4_HcalIn_ref.C"
#include "G4_Magnet.C"
#include "G4_HcalOut_ref.C"
#include "G4_FGEM_fsPHENIX.C"
#include "G4_FEMC.C"
#include "G4_FHCAL.C"
#include <g4decayer/EDecayType.hh>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4eval/PHG4DstCompressReco.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phfield/PHFieldConfig.h>
Functions
int make_piston (string name, PHG4Reco *g4Reco)
void RunLoadTest ()
void G4Init (bool do_svtx=true, bool do_cemc=true, bool do_hcalin=true, bool do_magnet=true, bool do_hcalout=true, bool do_pipe=true, bool do_FGEM=true, bool do_FEMC=true, bool do_FHCAL=true, int n_TPC_layers=40)
int G4Setup (const int absorberactive=0, const string &field="1.5", const EDecayType decayType=EDecayType::kAll, const bool do_svtx=true, const bool do_cemc=true, const bool do_hcalin=true, const bool do_magnet=true, const bool do_hcalout=true, const bool do_pipe=true, const bool do_FGEM=true, const bool do_FEMC=false, const bool do_FHCAL=false, const float magfield_rescale=1.0)
void ShowerCompress (int verbosity=0)
void DstCompress (Fun4AllDstOutputManager *out)
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 345 of file G4Setup_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 345 of file G4Setup_fsPHENIX.C
References Fun4AllDstOutputManager::StripNode().
void G4Init (bool do_svtx = true, bool do_cemc = true, bool do_hcalin = true, bool do_magnet = true, bool do_hcalout = true, bool do_pipe = true, bool do_FGEM = true, bool do_FEMC = true, bool do_FHCAL = true, int n_TPC_layers = 40)
Definition at line 30 of file G4Setup_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 30 of file G4Setup_fsPHENIX.C
References CEmcInit(), FEMCInit(), FGEM_Init(), FHCALInit(), HCalInnerInit(), HCalOuterInit(), MagnetInit(), PipeInit(), and TrackingInit().
int G4Setup (const int absorberactive = 0, const string & field = "1.5", const EDecayType decayType = EDecayType::kAll, const bool do_svtx = true, const bool do_cemc = true, const bool do_hcalin = true, const bool do_magnet = true, const bool do_hcalout = true, const bool do_pipe = true, const bool do_FGEM = true, const bool do_FEMC = false, const bool do_FHCAL = false, const float magfield_rescale = 1.0)
Definition at line 97 of file G4Setup_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 97 of file G4Setup_fsPHENIX.C
References PHG4DetectorSubsystem::BlackHole(), CEmc(), FEMCSetup(), FGEMSetup(), FHCALSetup(), PHFieldConfig::Field3DCartesian, PHG4Reco::GetWorldSizeZ(), HCalInner(), HCalOuter(), Fun4AllServer::instance(), kAll, PHFieldConfig::kField2D, Magnet(), no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Pipe(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4Reco::save_DST_geometry(), PHG4DetectorSubsystem::set_double_param(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4DetectorSubsystem::set_int_param(), PHG4Reco::set_rapidity_coverage(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and Tracking().
int make_piston (string name, PHG4Reco * g4Reco)
Definition at line 376 of file G4Setup_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 376 of file G4Setup_fsPHENIX.C
References PIPE::be_pipe_radius, PIPE::be_pipe_thickness, PHG4Sector::Sector_Geometry::eta_to_polar_angle(), name, PHG4DetectorSubsystem::OverlapCheck(), Acts::Test::pos, PHG4Reco::registerSubsystem(), Acts::UnitConstants::s, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and PHG4ConeSubsystem::SuperDetector().
void RunLoadTest ()
Definition at line 28 of file G4Setup_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 28 of file G4Setup_fsPHENIX.C
void ShowerCompress (int verbosity = 0)
Definition at line 291 of file G4Setup_fsPHENIX.C.
View newest version in sPHENIX GitHub at line 291 of file G4Setup_fsPHENIX.C
References PHG4DstCompressReco::AddCellContainer(), PHG4DstCompressReco::AddHitContainer(), PHG4DstCompressReco::AddTowerContainer(), compress(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().