EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_GEM_EIC.C File Reference
G4_GEM_EIC.C File Reference
#include "GlobalVariables.C"
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <TMath.h>
#include <string>
Namespaces
namespace Enable
Functions
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
int make_LANL_FST_station (string name, PHG4Reco *g4Reco, double zpos, double Rmin, double Rmax)
void EGEM_Init ()
void FGEM_Init ()
void EGEMSetup (PHG4Reco *g4Reco)
void FGEMSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.245)
Variables
static bool Enable::EGEM = false
static bool Enable::FGEM = false
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
void EGEM_Init ()
Definition at line 27 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 27 of file G4_GEM_EIC.C
References max, BlackHoleGeometry::max_radius, min, and BlackHoleGeometry::min_z.
Referenced by G4Init().
void EGEMSetup (PHG4Reco * g4Reco)
Definition at line 40 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 40 of file G4_GEM_EIC.C
References make_GEM_station(), and thickness.
Referenced by G4Setup().
void FGEM_Init ()
Definition at line 34 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 34 of file G4_GEM_EIC.C
References max, BlackHoleGeometry::max_radius, and BlackHoleGeometry::max_z.
void FGEMSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.245)
LANL FST From Xuan Li
Definition at line 55 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 55 of file G4_GEM_EIC.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), cos(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), make_LANL_FST_station(), name, overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), and PHG4Sector::Sector_Geometry::Unit_cm().
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8)
Definition at line 293 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 293 of file G4_GEM_EIC.C
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, and PHG4Sector::Sector_Geometry::Unit_cm().
int make_LANL_FST_station (string name, PHG4Reco * g4Reco, double zpos, double Rmin, double Rmax)
Definition at line 205 of file G4_GEM_EIC.C.
View newest version in sPHENIX GitHub at line 205 of file G4_GEM_EIC.C
References PHG4Sector::Sector_Geometry::AddLayer(), eic::cm, PHG4Sector::Sector_Geometry::ConeEdge(), Acts::UnitConstants::e, PHG4SectorSubsystem::get_geometry(), eic::mm, overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, eic::um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by FGEMSetup().