EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_PlugDoor_EIC.C File Reference
G4_PlugDoor_EIC.C File Reference
#include "GlobalVariables.C"
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
namespace G4PLUGDOOR
Functions
void PlugDoorInit ()
void PlugDoor (PHG4Reco *g4Reco, const int absorberactive=0, int verbosity=0)
Variables
static bool Enable::PLUGDOOR = false
const double G4PLUGDOOR::z_1 = 330.81
const double G4PLUGDOOR::z_2 = 360.81
const double G4PLUGDOOR::r_1 = 30
const double G4PLUGDOOR::r_2 = 263.5
const double G4PLUGDOOR::length = z_2 - z_1
const double G4PLUGDOOR::place_z = -(z_1 + z_2) / 2.
Function Documentation
void PlugDoor (PHG4Reco * g4Reco, const int absorberactive = 0, int verbosity = 0)
Definition at line 35 of file G4_PlugDoor_EIC.C.
View newest version in sPHENIX GitHub at line 35 of file G4_PlugDoor_EIC.C
References G4PLUGDOOR::length, material, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), G4PLUGDOOR::place_z, G4PLUGDOOR::r_1, G4PLUGDOOR::r_2, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), and PHG4DetectorSubsystem::SetActive().
void PlugDoorInit ()
Definition at line 29 of file G4_PlugDoor_EIC.C.
View newest version in sPHENIX GitHub at line 29 of file G4_PlugDoor_EIC.C
References G4PLUGDOOR::length, max, BlackHoleGeometry::max_radius, min, BlackHoleGeometry::min_z, G4PLUGDOOR::place_z, and G4PLUGDOOR::r_2.