EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_CEmc_EIC.C File Reference
G4_CEmc_EIC.C File Reference
#include "GlobalVariables.C"
#include <g4calo/RawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4CylinderCellReco.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <cmath>
Namespaces
namespace Enable
namespace G4CEMC
Enumerations
enum G4CEMC::enu_Cemc_clusterizer { G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer }
Functions
void CEmcInit (const int nslats=1)
double CEmc (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
void CEMC_Cells (int verbosity=0)
void CEMC_Towers (int verbosity=0)
void CEMC_Clusters (int verbosity=0)
void CEMC_Eval (std::string outputfile, int verbosity=0)
Variables
static bool Enable::CEMC = false
double G4CEMC::cemcdepth = 9
double G4CEMC::scint_width = 0.05
double G4CEMC::tungs_width = 0.245
double G4CEMC::electronics_width = 0.5
int G4CEMC::min_cemc_layer = 1
int G4CEMC::max_cemc_layer = 41
double G4CEMC::topradius = 106.8
double G4CEMC::bottomradius = 95
double G4CEMC::negrapidity = -1.5
double G4CEMC::posrapidity = 1.24
enu_Cemc_clusterizer G4CEMC::Cemc_clusterizer = kCemcTemplateClusterizer
Function Documentation
double CEmc (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
Definition at line 73 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 73 of file G4_CEmc_EIC.C
References G4CEMC::bottomradius, cemc, G4CEMC::electronics_width, M_PI, max, G4CEMC::max_cemc_layer, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, G4CEMC::min_cemc_layer, BlackHoleGeometry::min_z, G4CEMC::negrapidity, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), G4CEMC::posrapidity, PHG4Reco::registerSubsystem(), G4CEMC::scint_width, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), G4CEMC::topradius, G4CEMC::tungs_width, z1, and z2.
Referenced by G4Setup().
void CEMC_Cells (int verbosity = 0)
Definition at line 208 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 208 of file G4_CEmc_EIC.C
References PHG4CylinderCellReco::cellsize(), PHG4CylinderCellReco::Detector(), Fun4AllServer::instance(), M_PI, G4CEMC::max_cemc_layer, G4CEMC::min_cemc_layer, no_overlapp, Fun4AllServer::registerSubsystem(), G4CEMC::scint_width, G4CEMC::tungs_width, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void CEMC_Clusters (int verbosity = 0)
Definition at line 265 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 265 of file G4_CEmc_EIC.C
References G4CEMC::Cemc_clusterizer, RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), exit(), Fun4AllServer::instance(), G4CEMC::kCemcGraphClusterizer, G4CEMC::kCemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::set_threshold_energy(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void CEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 295 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 295 of file G4_CEmc_EIC.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void CEMC_Towers (int verbosity = 0)
Definition at line 229 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 229 of file G4_CEmc_EIC.C
References RawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void CEmcInit (const int nslats = 1)
Definition at line 69 of file G4_CEmc_EIC.C.
View newest version in sPHENIX GitHub at line 69 of file G4_CEmc_EIC.C
Referenced by G4Init().