EIC Software: fun4all_g4jleic/blob/master/macros/Fun4All_G4_JLeic.C File Reference
Fun4All_G4_JLeic.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4ParticleGeneratorVectorMeson.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/HepMCNodeReader.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <phool/recoConsts.h>
#include <phpythia6/PHPythia6.h>
#include <phpythia8/PHPythia8.h>
#include <phhepmc/Fun4AllHepMCPileupInputManager.h>
#include <phhepmc/Fun4AllHepMCInputManager.h>
#include "G4Setup_JLeic.C"
#include "DisplayOn.C"
#include "G4_Tracking_EIC.C"
Functions
int Fun4All_G4_JLeic (const int nEvents=1, const char *inputFile="/sphenix/data/data02/review_2017-08-02/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root", const char *outputFile="G4JLeic.root", const char *embed_input_file="/sphenix/data/data02/review_2017-08-02/sHijing/fm_0-4.list")
void RunFFALoadTest ()
Function Documentation
int Fun4All_G4_JLeic (const int nEvents = 1, const char * inputFile = "/sphenix/data/data02/review_2017-08-02/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root", const char * outputFile = "G4JLeic.root", const char * embed_input_file = "/sphenix/data/data02/review_2017-08-02/sHijing/fm_0-4.list")
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 39 of file Fun4All_G4_JLeic.C.
View newest version in sPHENIX GitHub at line 39 of file Fun4All_G4_JLeic.C
References PHG4ParticleGeneratorVectorMeson::add_decay_particles(), PHG4SimpleEventGenerator::add_particles(), Fun4AllInputManager::AddFile(), Fun4AllInputManager::AddListFile(), G4HitNtuple::AddNode(), DisplayOn(), Acts::UnitConstants::e, PHG4ParticleGeneratorBase::Embed(), Fun4AllServer::End(), exit(), Fun4AllInputManager::fileopen(), Fun4AllServer::fileopen(), G4Init(), G4Setup(), recoConsts::instance(), Fun4AllServer::instance(), jleic_shiftz, kAll, magfield, Fun4AllBase::Name(), nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), Fun4AllHepMCPileupInputManager::set_collision_rate(), PHPythia6::set_config_file(), PHPythia8::set_config_file(), PHG4ParticleGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHFlag::set_IntFlag(), PHG4ParticleGeneratorVectorMeson::set_mass(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4ParticleGeneratorVectorMeson::set_pt_range(), PHG4SimpleEventGenerator::set_pt_range(), PHG4ParticleGeneratorVectorMeson::set_rapidity_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHPythia6::set_reuse_vertex(), PHPythia8::set_reuse_vertex(), Fun4AllHepMCPileupInputManager::set_time_window(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGeneratorVectorMeson::set_width(), PHG4ParticleGenerator::set_z_range(), Tracking_Eval(), Tracking_Reco(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
void RunFFALoadTest ()
Definition at line 470 of file Fun4All_G4_JLeic.C.
View newest version in sPHENIX GitHub at line 470 of file Fun4All_G4_JLeic.C