EIC Software: MakeActsGeometry Class Reference
MakeActsGeometry Class Reference
#include <fun4all_coresoftware/blob/master/offline/packages/trackreco/MakeActsGeometry.h>
Public Member Functions
MakeActsGeometry (const std::string &name="MakeActsGeometry")
Default constructor.
~MakeActsGeometry ()
Destructor.
int buildAllGeometry (PHCompositeNode *topNode)
Main function to build all acts geometry for use in the fitting modules.
void editTPCGeometry (PHCompositeNode *topNode)
Functions to edit TGeoManager to include TPC boxes.
void addActsTpcSurfaces (TGeoVolume *tpc_gas_vol, TGeoManager *geoManager)
void setVerbosity (int verbosity)
std::map< TrkrDefs::hitsetkey,
Surface > getSurfaceMapSilicon ()
std::map< TrkrDefs::hitsetkey,
std::vector< Surface > > getSurfaceMapTpc ()
std::map< TrkrDefs::hitsetkey,
TGeoNode * > getTGeoNodeMap ()
std::vector< std::shared_ptr
< FW::IContextDecorator > > getContextDecorators ()
TrackingGeometry getTGeometry ()
Getters for acts geometry that is needed by fitter functions.
FW::Options::BFieldVariant getMagField ()
Acts::MagneticFieldContext getMagFieldContext ()
Acts::CalibrationContext getCalibContext ()
Acts::GeometryContext getGeoContext ()
Surface getTpcSurfaceFromCoords (TrkrDefs::hitsetkey hitsetkey, std::vector< double > &world)
Private Member Functions
int getNodes (PHCompositeNode *)
Get all the nodes.
int createNodes (PHCompositeNode *)
Create New nodes.
void buildActsSurfaces ()
Silicon layers made by BuildSiliconLayers and its helper functions.
void makeGeometry (int argc, char *argv[], FW::IBaseDetector &detector)
Function that mimics ActsFW::GeometryExampleBase.
void getInttKeyFromNode (TGeoNode *gnode)
Get hitsetkey from TGeoNode for each detector geometry.
void getMvtxKeyFromNode (TGeoNode *gnode)
void getTpcKeyFromNode (TGeoNode *gnode)
void makeMvtxMapPairs (TrackingVolumePtr &mvtxVolume)
void makeInttMapPairs (TrackingVolumePtr &inttVolume)
void makeTpcMapPairs (TrackingVolumePtr &tpcVolume)
TrkrDefs::hitsetkey getMvtxHitSetKeyFromCoords (unsigned int layer, std::vector< double > &world)
Get subdetector hitsetkey from the local sensor unit coordinates.
TrkrDefs::hitsetkey getInttHitSetKeyFromCoords (unsigned int layer, std::vector< double > &world)
TrkrDefs::hitsetkey getTpcHitSetKeyFromCoords (std::vector< double > &world)
void isActive (TGeoNode *gnode, int nmax_print)
Helper diagnostic function for identifying active layers in subdetectors.
void makeTGeoNodeMap (PHCompositeNode *topNode)
Makes map of TrkrHitSetKey<–>TGeoNode.
Private Attributes
PHG4CylinderGeomContainer * m_geomContainerMvtx
Subdetector geometry containers for getting layer information.
PHG4CylinderGeomContainer * m_geomContainerIntt
PHG4CylinderCellGeomContainer * m_geomContainerTpc
TGeoManager * m_geoManager
std::vector< std::shared_ptr
< FW::IContextDecorator > > m_contextDecorators
Acts Context decorators, which may contain e.g. calibration information.
std::map< TrkrDefs::hitsetkey,
TGeoNode * > m_clusterNodeMap
Several maps that connect Acts world to sPHENIX G4 world.
std::map< TrkrDefs::hitsetkey,
Surface > m_clusterSurfaceMapSilicon
std::map< TrkrDefs::hitsetkey,
std::vector< Surface > > m_clusterSurfaceMapTpcEdit
std::map< TrkrDefs::cluskey,
Surface > m_clusterSurfaceMapTpc
const unsigned int m_nTpcModulesPerLayer = 12
const unsigned int m_nTpcSides = 2
double m_minSurfZ
TPC Acts::Surface subdivisions.
double m_maxSurfZ
unsigned int m_nSurfZ
unsigned int m_nSurfPhi
double m_surfStepPhi
double m_surfStepZ
double m_moduleStepPhi
double m_modulePhiStart
int nprint_tpc
Debugger for printing out tpc active volumes.
const double m_minRadius [m_nTpcSectors] = {30.0, 40.0, 60.0}
const double m_maxRadius [m_nTpcSectors] = {40.0, 60.0, 77.0}
double layer_thickness_sector [m_nTpcSectors] = {0}
double m_layerRadius [m_nTpcLayers] = {0}
double m_layerThickness [m_nTpcLayers] = {0}
const double half_width_clearance_thick = 0.4999
const double half_width_clearance_phi = 0.4999
const double half_width_clearance_z = 0.4999
TGeoDetector m_detector
The acts geometry object.
TrackingGeometry m_tGeometry
Acts geometry objects that are needed to create (for example) the fitter.
FW::Options::BFieldVariant m_magneticField
Acts::GeometryContext m_geoCtxt
Acts::CalibrationContext m_calibContext
Acts::MagneticFieldContext m_magFieldContext
int m_verbosity
Verbosity value handed from PHActsSourceLinks.
Static Private Attributes
static const unsigned int m_nTpcLayers = 48
These don't change, we are building the tpc this way!
static const int m_nTpcSectors = 3
TPC TGeoManager editing box surfaces subdivisions.
Detailed Description
This class is responsible for building the ActsGeometry from the sPHENIX TGeometry. The code largely follows examples within the ACTFW code, specifically GeometryExampleBase.cpp. This class puts several nodes on the node tree which relate Acts::Surfaces to sPHENIX TGeo objects, for use in building Acts SourceLinks.
Definition at line 58 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 58 of file MakeActsGeometry.h
Constructor & Destructor Documentation
MakeActsGeometry::MakeActsGeometry (const std::string & name = "MakeActsGeometry")
Default constructor.
These are arbitrary tpc subdivisions, and may change Setup how TPC boxes will be built for Acts::Surfaces
Definition at line 70 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 70 of file MakeActsGeometry.cc
References layer_thickness_sector, m_layerRadius, m_layerThickness, m_maxRadius, m_maxSurfZ, m_minRadius, m_minSurfZ, m_modulePhiStart, m_moduleStepPhi, m_nSurfPhi, m_nSurfZ, m_nTpcModulesPerLayer, M_PI, m_surfStepPhi, m_surfStepZ, and nprint_tpc.
MakeActsGeometry::~MakeActsGeometry ()
Destructor.
Definition at line 103 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 103 of file MakeActsGeometry.cc
Member Function Documentation
void MakeActsGeometry::addActsTpcSurfaces (TGeoVolume * tpc_gas_vol, TGeoManager * geoManager)
Definition at line 214 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 214 of file MakeActsGeometry.cc
References cos(), half_width_clearance_phi, half_width_clearance_thick, half_width_clearance_z, m_layerRadius, m_layerThickness, m_modulePhiStart, m_moduleStepPhi, m_nSurfPhi, m_nSurfZ, m_nTpcLayers, m_nTpcModulesPerLayer, M_PI, m_surfStepPhi, m_surfStepZ, and m_verbosity.
Referenced by editTPCGeometry().
void MakeActsGeometry::buildActsSurfaces () private
Silicon layers made by BuildSiliconLayers and its helper functions.
Builds silicon layers and TPC geometry in the ACTS surface world
Definition at line 294 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 294 of file MakeActsGeometry.cc
References m_detector, and makeGeometry().
Referenced by buildAllGeometry().
int MakeActsGeometry::buildAllGeometry (PHCompositeNode * topNode)
Main function to build all acts geometry for use in the fitting modules.
Definition at line 106 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 106 of file MakeActsGeometry.cc
References buildActsSurfaces(), createNodes(), editTPCGeometry(), Fun4AllReturnCodes::EVENT_OK, getNodes(), and makeTGeoNodeMap().
Referenced by PHActsSourceLinks::InitRun().
int MakeActsGeometry::createNodes (PHCompositeNode * topNode) private
Create New nodes.
Definition at line 1058 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1058 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::EVENT_OK.
Referenced by buildAllGeometry().
void MakeActsGeometry::editTPCGeometry (PHCompositeNode * topNode)
Functions to edit TGeoManager to include TPC boxes.
Reset the geometry node, which we will recreate with the TPC edits
Definition at line 126 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 126 of file MakeActsGeometry.cc
References addActsTpcSurfaces(), PHGeomIOTGeo::ConstructTGeoManager(), PHGeomUtility::GetGeomIOTGeoNode(), PHGeomUtility::GetGeomTGeoNode(), PHGeomTGeo::isValid(), PHGeomIOTGeo::isValid(), m_verbosity, PHGeomTGeo::Reset(), PHGeomTGeo::SetGeometry(), and PHGeomUtility::UpdateIONode().
Referenced by buildAllGeometry().
Acts::CalibrationContext MakeActsGeometry::getCalibContext () inline
Definition at line 94 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 94 of file MakeActsGeometry.h
References m_calibContext.
Referenced by PHActsSourceLinks::InitRun().
std::vector<std::shared_ptr<FW::IContextDecorator> > MakeActsGeometry::getContextDecorators () inline
Definition at line 87 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 87 of file MakeActsGeometry.h
References m_contextDecorators.
Acts::GeometryContext MakeActsGeometry::getGeoContext () inline
Definition at line 95 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 95 of file MakeActsGeometry.h
References m_geoCtxt.
Referenced by PHActsSourceLinks::getInttLocalCoords(), PHActsSourceLinks::getMvtxLocalCoords(), PHActsSourceLinks::getTpcLocalCoords(), and PHActsSourceLinks::InitRun().
TrkrDefs::hitsetkey MakeActsGeometry::getInttHitSetKeyFromCoords (unsigned int layer, std::vector< double > & world) private
Definition at line 772 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 772 of file MakeActsGeometry.cc
References CylinderGeomIntt::find_indices_from_segment_center(), CylinderGeomIntt::find_segment_center(), InttDefs::genHitSetKey(), PHG4CylinderGeomContainer::GetLayerGeom(), m_geomContainerIntt, and PHWHERE.
Referenced by makeInttMapPairs().
void MakeActsGeometry::getInttKeyFromNode (TGeoNode * gnode) private
Get hitsetkey from TGeoNode for each detector geometry.
Definition at line 857 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 857 of file MakeActsGeometry.cc
References exit(), InttDefs::genHitSetKey(), m_clusterNodeMap, m_verbosity, PHWHERE, Acts::Test::pos, and Acts::UnitConstants::s.
Referenced by makeTGeoNodeMap().
FW::Options::BFieldVariant MakeActsGeometry::getMagField () inline
Definition at line 92 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 92 of file MakeActsGeometry.h
References m_magneticField.
Referenced by PHActsSourceLinks::InitRun().
Acts::MagneticFieldContext MakeActsGeometry::getMagFieldContext () inline
Definition at line 93 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 93 of file MakeActsGeometry.h
References m_magFieldContext.
Referenced by PHActsSourceLinks::InitRun().
TrkrDefs::hitsetkey MakeActsGeometry::getMvtxHitSetKeyFromCoords (unsigned int layer, std::vector< double > & world) private
Get subdetector hitsetkey from the local sensor unit coordinates.
Definition at line 750 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 750 of file MakeActsGeometry.cc
References CylinderGeom_Mvtx::find_sensor_center(), MvtxDefs::genHitSetKey(), CylinderGeom_Mvtx::get_sensor_indices_from_world_coords(), PHG4CylinderGeomContainer::GetLayerGeom(), m_geomContainerMvtx, and PHWHERE.
Referenced by makeMvtxMapPairs().
void MakeActsGeometry::getMvtxKeyFromNode (TGeoNode * gnode) private
Definition at line 930 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 930 of file MakeActsGeometry.cc
References MvtxDefs::genHitSetKey(), m_clusterNodeMap, m_verbosity, Acts::Test::pos, and Acts::UnitConstants::s.
Referenced by makeTGeoNodeMap().
int MakeActsGeometry::getNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 1067 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1067 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, findNode::getClass(), PHGeomUtility::GetTGeoManager(), m_geoManager, m_geomContainerIntt, m_geomContainerMvtx, m_geomContainerTpc, and PHWHERE.
Referenced by buildAllGeometry().
std::map<TrkrDefs::hitsetkey,Surface> MakeActsGeometry::getSurfaceMapSilicon () inline
Definition at line 78 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 78 of file MakeActsGeometry.h
References m_clusterSurfaceMapSilicon.
Referenced by PHActsSourceLinks::getSurfaceFromClusterMap().
std::map<TrkrDefs::hitsetkey, std::vector<Surface> > MakeActsGeometry::getSurfaceMapTpc () inline
Definition at line 81 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 81 of file MakeActsGeometry.h
References m_clusterSurfaceMapTpcEdit.
TrackingGeometry MakeActsGeometry::getTGeometry () inline
Getters for acts geometry that is needed by fitter functions.
Definition at line 91 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 91 of file MakeActsGeometry.h
References m_tGeometry.
Referenced by PHActsSourceLinks::InitRun().
std::map<TrkrDefs::hitsetkey, TGeoNode*> MakeActsGeometry::getTGeoNodeMap () inline
Definition at line 84 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 84 of file MakeActsGeometry.h
References m_clusterNodeMap.
Referenced by PHActsSourceLinks::getNodeFromClusterMap().
TrkrDefs::hitsetkey MakeActsGeometry::getTpcHitSetKeyFromCoords (std::vector< double > & world) private
Definition at line 693 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 693 of file MakeActsGeometry.cc
References Fun4AllReturnCodes::ABORTEVENT, TpcDefs::genHitSetKey(), m_layerRadius, m_layerThickness, m_modulePhiStart, m_moduleStepPhi, m_nTpcLayers, m_nTpcModulesPerLayer, m_verbosity, and PHWHERE.
Referenced by makeTpcMapPairs().
void MakeActsGeometry::getTpcKeyFromNode (TGeoNode * gnode) private
Definition at line 926 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 926 of file MakeActsGeometry.cc
Referenced by makeTGeoNodeMap().
Surface MakeActsGeometry::getTpcSurfaceFromCoords (TrkrDefs::hitsetkey hitsetkey, std::vector< double > & world)
Gets tpc surface from a cluster coordinate and hitsetkey. Necessary since there are many tpc surfaces per read out module
Definition at line 651 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 651 of file MakeActsGeometry.cc
References exit(), m_clusterSurfaceMapTpcEdit, m_geoCtxt, m_surfStepPhi, m_surfStepZ, and PHWHERE.
Referenced by PHActsSourceLinks::getTpcLocalCoords().
void MakeActsGeometry::isActive (TGeoNode * gnode, int nmax_print) private
Helper diagnostic function for identifying active layers in subdetectors.
Definition at line 1004 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 1004 of file MakeActsGeometry.cc
References nprint_tpc.
Referenced by makeTGeoNodeMap().
void MakeActsGeometry::makeGeometry (int argc, char * argv[], FW::IBaseDetector & detector) private
Function that mimics ActsFW::GeometryExampleBase.
setup and parse options
Add specific options for this geometry
Now read the standard options
The geometry, material and decoration
Geometry is a pair of (tgeoTrackingGeometry, tgeoContextDecorators)
The detectors "MVTX" and "Silicon" and "TPC"
Setup the event and algorithm context
The geometry context
This is not executed because contextDecorators has size 0 Decorate the context
m_tGeometry is a TrackingGeometry pointer vol is a TrackingVolume pointer
Get the confined volumes in the highest tracking volume confinedVolumes is a shared_ptr<TrackingVolumeArray>
volumeVector is a std::vector<TrackingVolumePtrs>
We have several volumes to walk through with the tpc and silicon
This actually contains the silicon volumes
siliconVolumes is a shared_ptr<TrackingVolumeArray> Now get the individual TrackingVolumePtrs corresponding to each silicon volume
INTT only has one volume, so there is not an added volume extraction like for the MVTX
Same for the TPC - only one volume
Definition at line 318 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 318 of file MakeActsGeometry.cc
References FW::Options::addBFieldOptions(), FW::Options::addGeometryOptions(), FW::Options::addMaterialOptions(), FW::Options::addObjWriterOptions(), FW::IBaseDetector::addOptions(), FW::Options::addOutputOptions(), FW::Options::addSequencerOptions(), FW::Geometry::build(), FW::AlgorithmContext::calibContext, incremental_prev_tag::desc, FW::AlgorithmContext::geoContext, Acts::getDefaultLogger(), m_calibContext, m_contextDecorators, m_geoCtxt, m_magFieldContext, m_magneticField, m_tGeometry, m_verbosity, FW::AlgorithmContext::magFieldContext, FW::Options::makeDefaultOptions(), makeInttMapPairs(), makeMvtxMapPairs(), makeTpcMapPairs(), FW::Options::parse(), FW::Options::readBField(), FW::Options::readLogLevel(), SUCCESS, and nlohmann::to_string().
Referenced by buildActsSurfaces().
void MakeActsGeometry::makeInttMapPairs (TrackingVolumePtr & inttVolume) private
The Acts geometry builder combines layers 4 and 5 together, and layers 6 and 7 together. We need to use the radius to figure out which layer to use to get the layergeom
Definition at line 489 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 489 of file MakeActsGeometry.cc
References getInttHitSetKeyFromCoords(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), m_clusterSurfaceMapSilicon, m_geoCtxt, and m_verbosity.
Referenced by makeGeometry().
void MakeActsGeometry::makeMvtxMapPairs (TrackingVolumePtr & mvtxVolume) private
Make the Surface<–>TrkrDef::hitsetkey map pairs for each of the various subdetectors
Definition at line 572 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 572 of file MakeActsGeometry.cc
References MvtxDefs::getChipId(), getMvtxHitSetKeyFromCoords(), MvtxDefs::getStaveId(), m_clusterSurfaceMapSilicon, m_geoCtxt, and m_verbosity.
Referenced by makeGeometry().
void MakeActsGeometry::makeTGeoNodeMap (PHCompositeNode * topNode) private
Makes map of TrkrHitSetKey<–>TGeoNode.
Definition at line 795 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 795 of file MakeActsGeometry.cc
References getInttKeyFromNode(), getMvtxKeyFromNode(), getTpcKeyFromNode(), isActive(), m_geoManager, m_verbosity, PHWHERE, and tpc().
Referenced by buildAllGeometry().
void MakeActsGeometry::makeTpcMapPairs (TrackingVolumePtr & tpcVolume) private
Need to unfold each layer that Acts builds
surfaceVector is a vector of surfaces corresponding to the tpc layer that acts builds
convert to cm
If there is already an entry for this hitsetkey, add the surface to its corresponding vector
Otherwise make a new map entry
Definition at line 436 of file MakeActsGeometry.cc.
View newest version in sPHENIX GitHub at line 436 of file MakeActsGeometry.cc
References getTpcHitSetKeyFromCoords(), m_clusterSurfaceMapTpcEdit, and m_geoCtxt.
Referenced by makeGeometry().
void MakeActsGeometry::setVerbosity (int verbosity) inline
Definition at line 75 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 75 of file MakeActsGeometry.h
References m_verbosity.
Referenced by PHActsSourceLinks::InitRun().
Member Data Documentation
const double MakeActsGeometry::half_width_clearance_phi = 0.4999 private
Definition at line 184 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 184 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces().
const double MakeActsGeometry::half_width_clearance_thick = 0.4999 private
Definition at line 183 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 183 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces().
const double MakeActsGeometry::half_width_clearance_z = 0.4999 private
Definition at line 185 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 185 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces().
double MakeActsGeometry::layer_thickness_sector[m_nTpcSectors] = {0} private
Definition at line 178 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 178 of file MakeActsGeometry.h
Referenced by MakeActsGeometry().
Acts::CalibrationContext MakeActsGeometry::m_calibContext private
Definition at line 194 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 194 of file MakeActsGeometry.h
Referenced by getCalibContext(), and makeGeometry().
std::map<TrkrDefs::hitsetkey, TGeoNode*> MakeActsGeometry::m_clusterNodeMap private
Several maps that connect Acts world to sPHENIX G4 world.
Definition at line 151 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 151 of file MakeActsGeometry.h
Referenced by getInttKeyFromNode(), getMvtxKeyFromNode(), and getTGeoNodeMap().
std::map<TrkrDefs::hitsetkey, Surface> MakeActsGeometry::m_clusterSurfaceMapSilicon private
Definition at line 152 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 152 of file MakeActsGeometry.h
Referenced by getSurfaceMapSilicon(), makeInttMapPairs(), and makeMvtxMapPairs().
std::map<TrkrDefs::cluskey, Surface> MakeActsGeometry::m_clusterSurfaceMapTpc private
Definition at line 154 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 154 of file MakeActsGeometry.h
std::map<TrkrDefs::hitsetkey, std::vector<Surface> > MakeActsGeometry::m_clusterSurfaceMapTpcEdit private
Definition at line 153 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 153 of file MakeActsGeometry.h
Referenced by getSurfaceMapTpc(), getTpcSurfaceFromCoords(), and makeTpcMapPairs().
std::vector<std::shared_ptr<FW::IContextDecorator> > MakeActsGeometry::m_contextDecorators private
Acts Context decorators, which may contain e.g. calibration information.
Definition at line 148 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 148 of file MakeActsGeometry.h
Referenced by getContextDecorators(), and makeGeometry().
TGeoDetector MakeActsGeometry::m_detector private
The acts geometry object.
Definition at line 188 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 188 of file MakeActsGeometry.h
Referenced by buildActsSurfaces().
Acts::GeometryContext MakeActsGeometry::m_geoCtxt private
Definition at line 193 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 193 of file MakeActsGeometry.h
Referenced by getGeoContext(), getTpcSurfaceFromCoords(), makeGeometry(), makeInttMapPairs(), makeMvtxMapPairs(), and makeTpcMapPairs().
TGeoManager* MakeActsGeometry::m_geoManager private
Definition at line 145 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 145 of file MakeActsGeometry.h
Referenced by getNodes(), and makeTGeoNodeMap().
PHG4CylinderGeomContainer* MakeActsGeometry::m_geomContainerIntt private
Definition at line 142 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 142 of file MakeActsGeometry.h
Referenced by getInttHitSetKeyFromCoords(), and getNodes().
PHG4CylinderGeomContainer* MakeActsGeometry::m_geomContainerMvtx private
Subdetector geometry containers for getting layer information.
Definition at line 141 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 141 of file MakeActsGeometry.h
Referenced by getMvtxHitSetKeyFromCoords(), and getNodes().
PHG4CylinderCellGeomContainer* MakeActsGeometry::m_geomContainerTpc private
Definition at line 143 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 143 of file MakeActsGeometry.h
Referenced by getNodes().
double MakeActsGeometry::m_layerRadius[m_nTpcLayers] = {0} private
Definition at line 179 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 179 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and MakeActsGeometry().
double MakeActsGeometry::m_layerThickness[m_nTpcLayers] = {0} private
Definition at line 180 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 180 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and MakeActsGeometry().
Acts::MagneticFieldContext MakeActsGeometry::m_magFieldContext private
Definition at line 195 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 195 of file MakeActsGeometry.h
Referenced by getMagFieldContext(), and makeGeometry().
FW::Options::BFieldVariant MakeActsGeometry::m_magneticField private
Definition at line 192 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 192 of file MakeActsGeometry.h
Referenced by getMagField(), and makeGeometry().
const double MakeActsGeometry::m_maxRadius[m_nTpcSectors] = {40.0, 60.0, 77.0} private
Definition at line 177 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 177 of file MakeActsGeometry.h
Referenced by MakeActsGeometry().
double MakeActsGeometry::m_maxSurfZ private
Definition at line 163 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 163 of file MakeActsGeometry.h
Referenced by MakeActsGeometry().
const double MakeActsGeometry::m_minRadius[m_nTpcSectors] = {30.0, 40.0, 60.0} private
Definition at line 176 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 176 of file MakeActsGeometry.h
Referenced by MakeActsGeometry().
double MakeActsGeometry::m_minSurfZ private
TPC Acts::Surface subdivisions.
Definition at line 162 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 162 of file MakeActsGeometry.h
Referenced by MakeActsGeometry().
double MakeActsGeometry::m_modulePhiStart private
Definition at line 169 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 169 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and MakeActsGeometry().
double MakeActsGeometry::m_moduleStepPhi private
Definition at line 168 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 168 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and MakeActsGeometry().
unsigned int MakeActsGeometry::m_nSurfPhi private
Definition at line 165 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 165 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), and MakeActsGeometry().
unsigned int MakeActsGeometry::m_nSurfZ private
Definition at line 164 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 164 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), and MakeActsGeometry().
const unsigned int MakeActsGeometry::m_nTpcLayers = 48 static private
These don't change, we are building the tpc this way!
Definition at line 157 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 157 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), and getTpcHitSetKeyFromCoords().
const unsigned int MakeActsGeometry::m_nTpcModulesPerLayer = 12 private
Definition at line 158 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 158 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcHitSetKeyFromCoords(), and MakeActsGeometry().
const int MakeActsGeometry::m_nTpcSectors = 3 static private
TPC TGeoManager editing box surfaces subdivisions.
Definition at line 175 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 175 of file MakeActsGeometry.h
const unsigned int MakeActsGeometry::m_nTpcSides = 2 private
Definition at line 159 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 159 of file MakeActsGeometry.h
double MakeActsGeometry::m_surfStepPhi private
Definition at line 166 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 166 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcSurfaceFromCoords(), and MakeActsGeometry().
double MakeActsGeometry::m_surfStepZ private
Definition at line 167 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 167 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), getTpcSurfaceFromCoords(), and MakeActsGeometry().
TrackingGeometry MakeActsGeometry::m_tGeometry private
Acts geometry objects that are needed to create (for example) the fitter.
Definition at line 191 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 191 of file MakeActsGeometry.h
Referenced by getTGeometry(), and makeGeometry().
int MakeActsGeometry::m_verbosity private
Verbosity value handed from PHActsSourceLinks.
Definition at line 198 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 198 of file MakeActsGeometry.h
Referenced by addActsTpcSurfaces(), editTPCGeometry(), getInttKeyFromNode(), getMvtxKeyFromNode(), getTpcHitSetKeyFromCoords(), makeGeometry(), makeInttMapPairs(), makeMvtxMapPairs(), makeTGeoNodeMap(), and setVerbosity().
int MakeActsGeometry::nprint_tpc private
Debugger for printing out tpc active volumes.
Definition at line 172 of file MakeActsGeometry.h.
View newest version in sPHENIX GitHub at line 172 of file MakeActsGeometry.h
Referenced by isActive(), and MakeActsGeometry().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/trackreco/MakeActsGeometry.h
fun4all_coresoftware/blob/master/offline/packages/trackreco/MakeActsGeometry.cc