EIC Software: fun4all_g4jleic/blob/master/macros/G4Setup_JLeic.C File Reference
G4Setup_JLeic.C File Reference
#include "G4_Pipe.C"
#include "G4_VTX.C"
#include "G4_CTD.C"
#include "G4_Magnet.C"
#include "G4_Gem.C"
#include "G4_JLDIRC.C"
#include "G4_Barrel_Hcal.C"
#include "G4_BeamLine.C"
#include "G4_DRich.C"
#include "G4_EndCap_Electron.C"
#include "G4_EndCap_Hadron.C"
#include <g4eval/PHG4DstCompressReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4decayer/EDecayType.hh>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <phfield/PHFieldConfig.h>
#include <g4main/HepMCNodeReader.h>
Functions
void RunLoadTest ()
void G4Init (const bool do_ctd=true, const bool do_vtx=true, const bool do_magnet=true, const bool do_pipe=true, const bool do_gem=true, const bool do_jldirc=true, const bool do_barrel_hcal=true, const bool do_drich=true, const bool do_endcap_electron=true, const bool do_endcap_hadron=true, const bool do_beamline=true)
int G4Setup (const int absorberactive=0, const string &field="2.0", const EDecayType decayType=EDecayType::kAll, const bool do_ctd=true, const bool do_vtx=true, const bool do_magnet=true, const bool do_pipe=true, const bool do_gem=true, const bool do_jldirc=true, const bool do_barrel_hcal=true, const bool do_drich=true, const bool do_endcap_electron=true, const bool do_endcap_hadron=true, const bool do_beamline=true, const float magfield_rescale=1.0)
Function Documentation
void G4Init (const bool do_ctd = true, const bool do_vtx = true, const bool do_magnet = true, const bool do_pipe = true, const bool do_gem = true, const bool do_jldirc = true, const bool do_barrel_hcal = true, const bool do_drich = true, const bool do_endcap_electron = true, const bool do_endcap_hadron = true, const bool do_beamline = true)
Definition at line 37 of file G4Setup_JLeic.C.
View newest version in sPHENIX GitHub at line 37 of file G4Setup_JLeic.C
References Barrel_HcalInit(), BeamLineInit(), CTDInit(), DRichInit(), EndCap_ElectronInit(), EndCap_HadronInit(), GemInit(), JLDIRCInit(), MagnetInit(), and PipeInit().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), Fun4All_G4_JLeic(), and Fun4All_G4_sPHENIX().
int G4Setup (const int absorberactive = 0, const string & field = "2.0", const EDecayType decayType = EDecayType::kAll, const bool do_ctd = true, const bool do_vtx = true, const bool do_magnet = true, const bool do_pipe = true, const bool do_gem = true, const bool do_jldirc = true, const bool do_barrel_hcal = true, const bool do_drich = true, const bool do_endcap_electron = true, const bool do_endcap_hadron = true, const bool do_beamline = true, const float magfield_rescale = 1.0)
Definition at line 111 of file G4Setup_JLeic.C.
View newest version in sPHENIX GitHub at line 111 of file G4Setup_JLeic.C
References Barrel_Hcal(), BeamLine(), PHG4DetectorSubsystem::BlackHole(), CTD(), DRich(), EndCap_Electron(), EndCap_Hadron(), PHFieldConfig::Field3DCartesian, Gem(), PHG4Reco::GetWorldSizeZ(), Fun4AllServer::instance(), JLDIRC(), kAll, PHFieldConfig::kField2D, Magnet(), no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Pipe(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4DetectorSubsystem::set_int_param(), PHG4Reco::set_rapidity_coverage(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and VTX().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), Fun4All_G4_JLeic(), and Fun4All_G4_sPHENIX().
void RunLoadTest ()
Definition at line 35 of file G4Setup_JLeic.C.
View newest version in sPHENIX GitHub at line 35 of file G4Setup_JLeic.C