EIC Software: eic-smear/blob/master/tests/qaplots.cxx File Reference
qaplots.cxx File Reference
#include "qaplots.hh"
#include <eicsmear/functions.h>
#include <eicsmear/smear/functions.h>
#include "eicsmear/erhic/EventBase.h"
#include "eicsmear/erhic/EventPythia.h"
#include "eicsmear/erhic/Particle.h"
#include "eicsmear/smear/EventSmear.h"
#include "eicsmear/smear/EventS.h"
#include "eicsmear/smear/Smear.h"
#include "eicsmear/smear/ParticleMCS.h"
#include "ePHENIXDetector.h"
#include "eicsmear/smear/Detector.h"
#include <TSystem.h>
#include <TDatabasePDG.h>
#include <TFile.h>
#include <TChain.h>
#include <TCanvas.h>
#include <TProfile.h>
#include <TLegend.h>
#include <TText.h>
#include <TStyle.h>
#include <string>
#include <iomanip>
#include <cctype>
#include <exception>
#include <vector>
#include <map>
Functions
Smear::Detector BuildHandBookDetector ()
Smear::Detector BuildPerfectDetector ()
Smear::Detector BuildNaiveHandBookDetector ()
Smear::Detector BuildZeus ()
Smear::Detector BuildBeAST ()
static const TString getrootname (const qaparameters &qapars)
static void initializepidqabook (const qaparameters &qapars, map< int, pidqacollection > &qabook)
static void initializeeventqa (const qaparameters &qapars, eventqacollection &eventqa)
static void FillEventQA (eventqacollection &eventqa, const erhic::EventMC *const inEvent, const Smear::Event *const inEventS)
static void FillParticleQA (map< int, pidqacollection > &qabook, const Particle *const inParticle, const Smear::ParticleMCS *const inParticleS)
static void PlotQA (const qaparameters &qapars, eventqacollection &eventqa, map< int, pidqacollection > &qabook)
int main (int argc, char *argv[])
qaparameters ParseArguments (int argc, char *argv[])
Function Documentation
Smear::Detector BuildBeAST ()
Definition at line 12 of file smearBeAST.cxx.
View newest version in sPHENIX GitHub at line 12 of file smearBeAST.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddParticle(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kNeutral, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by main().
Smear::Detector BuildHandBookDetector ()
Definition at line 42 of file smearHandBook.cxx.
View newest version in sPHENIX GitHub at line 42 of file smearHandBook.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by main().
Smear::Detector BuildNaiveHandBookDetector ()
Definition at line 25 of file smearNaiveHandBook.cxx.
View newest version in sPHENIX GitHub at line 25 of file smearNaiveHandBook.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), Smear::kCharged, Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, Smear::Acceptance::SetCharge(), Smear::Detector::SetEventKinematicsCalculator(), Smear::Acceptance::SetGenre(), and ThetaFromEta().
Referenced by main().
Smear::Detector BuildPerfectDetector ()
Definition at line 30 of file PerfectDetector.cxx.
View newest version in sPHENIX GitHub at line 30 of file PerfectDetector.cxx
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), etaToTheta(), Smear::kE, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, phi, pid, Smear::Detector::SetEventKinematicsCalculator(), and ds::theta.
Referenced by main().
Smear::Detector BuildZeus ()
Smearing parameterisations for the ZEUS detector.
See JHEP05 (2009) 108.
Note: you must gSystem->Load("libeicsmear") BEFORE loading this script.
Definition at line 45 of file ZEUSDetector.cpp.
View newest version in sPHENIX GitHub at line 45 of file ZEUSDetector.cpp
References Smear::Smearer::Accept, Smear::Detector::AddDevice(), Smear::Acceptance::AddZone(), degreesToRadians(), etaToTheta(), Smear::kE, Smear::kElectromagnetic, Smear::kHadronic, Smear::kP, Smear::kPhi, Smear::kTheta, momentum, phi, Smear::Detector::SetEventKinematicsCalculator(), and ds::theta.
Referenced by main().
void FillEventQA (eventqacollection & eventqa, const erhic::EventMC *const inEvent, const Smear::Event *const inEventS) static
Definition at line 181 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 181 of file qaplots.cxx
References kdfinder::abs(), eventqacollection::delQ2_DA, eventqacollection::delQ2_JB, eventqacollection::delQ2_NM, eventqacollection::delx_DA, eventqacollection::delx_JB, eventqacollection::delx_NM, eventqacollection::dely_DA, eventqacollection::dely_JB, eventqacollection::dely_NM, erhic::EventDis::GetQ2(), erhic::EventDis::GetQ2DoubleAngle(), erhic::EventDis::GetQ2JacquetBlondel(), erhic::EventDis::GetX(), erhic::EventDis::GetXDoubleAngle(), erhic::EventDis::GetXJacquetBlondel(), erhic::EventDis::GetY(), erhic::EventDis::GetYDoubleAngle(), erhic::EventDis::GetYJacquetBlondel(), eventqacollection::missedQ2_DA, eventqacollection::missedQ2_JB, eventqacollection::missedQ2_NM, eventqacollection::missedx_DA, eventqacollection::missedx_JB, eventqacollection::missedx_NM, eventqacollection::missedy_DA, eventqacollection::missedy_JB, eventqacollection::missedy_NM, eventqacollection::Q2_DA, eventqacollection::Q2_JB, eventqacollection::Q2_NM, eventqacollection::x_DA, eventqacollection::x_JB, eventqacollection::x_NM, eventqacollection::y_DA, eventqacollection::y_JB, and eventqacollection::y_NM.
void FillParticleQA (map< int, pidqacollection > & qabook, const Particle *const inParticle, const Smear::ParticleMCS *const inParticleS) static
Definition at line 221 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 221 of file qaplots.cxx
References Smear::ParticleMCS::GetE(), erhic::ParticleMCbase::GetE(), Smear::ParticleMCS::GetEta(), erhic::ParticleMCbase::GetEta(), Smear::ParticleMCS::GetP(), erhic::ParticleMCbase::GetP(), erhic::ParticleMCbase::GetPdgCode(), Smear::ParticleMCS::GetPhi(), erhic::ParticleMCbase::GetPhi(), Smear::ParticleMCS::GetTheta(), erhic::ParticleMCbase::GetTheta(), and pid.
const TString getrootname (const qaparameters & qapars) static
Definition at line 321 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 321 of file qaplots.cxx
References qaparameters::nevents, qaparameters::outpath, and qaparameters::txtfilename.
Referenced by main().
void initializeeventqa (const qaparameters & qapars, eventqacollection & eventqa) static
Definition at line 422 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 422 of file qaplots.cxx
References eventqacollection::delQ2_DA, eventqacollection::delQ2_JB, eventqacollection::delQ2_NM, eventqacollection::delx_DA, eventqacollection::delx_JB, eventqacollection::delx_NM, eventqacollection::dely_DA, eventqacollection::dely_JB, eventqacollection::dely_NM, qaparameters::detstring, Acts::UnitConstants::e, eventqacollection::Q2_DA, eventqacollection::Q2_JB, eventqacollection::Q2_NM, Acts::UnitConstants::s, eventqacollection::x_DA, eventqacollection::x_JB, eventqacollection::x_NM, xmax, xmin, eventqacollection::y_DA, eventqacollection::y_JB, eventqacollection::y_NM, ymax, and ymin.
Referenced by main().
void initializepidqabook (const qaparameters & qapars, map< int, pidqacollection > & qabook) static
Definition at line 346 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 346 of file qaplots.cxx
References kdfinder::abs(), qaparameters::detstring, phibins, phimin, pid, qaparameters::pids, and Acts::UnitConstants::s.
int main (int argc, char * argv[])
Definition at line 61 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 61 of file qaplots.cxx
References BuildBeAST(), BuildEphoenix(), BuildHandBookDetector(), BuildNaiveHandBookDetector(), BuildPerfectDetector(), BuildTree(), BuildZeus(), qaparameters::detstring, getrootname(), initializeeventqa(), qaparameters::nevents, qaparameters::outfilebase, qaparameters::outpath, ParseArguments(), qaparameters::pids, SmearTree(), and qaparameters::txtfilename.
qaparameters ParseArguments (int argc, char * argv[])
Definition at line 269 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 269 of file qaplots.cxx
References c, qaparameters::detstring, Acts::UnitConstants::e, qaparameters::nevents, qaparameters::outfilebase, qaparameters::pids, and qaparameters::txtfilename.
Referenced by main().
void PlotQA (const qaparameters & qapars, eventqacollection & eventqa, map< int, pidqacollection > & qabook) static
Definition at line 521 of file qaplots.cxx.
View newest version in sPHENIX GitHub at line 521 of file qaplots.cxx
References eventqacollection::delQ2_DA, eventqacollection::delQ2_JB, eventqacollection::delQ2_NM, eventqacollection::delx_DA, eventqacollection::delx_JB, eventqacollection::delx_NM, eventqacollection::dely_DA, eventqacollection::dely_JB, eventqacollection::dely_NM, qaparameters::detstring, eventqacollection::missedQ2_DA, eventqacollection::missedQ2_JB, eventqacollection::missedQ2_NM, eventqacollection::missedx_DA, eventqacollection::missedx_JB, eventqacollection::missedx_NM, eventqacollection::missedy_DA, eventqacollection::missedy_JB, eventqacollection::missedy_NM, qaparameters::outfilebase, pid, eventqacollection::Q2_DA, eventqacollection::Q2_JB, eventqacollection::Q2_NM, t, qaparameters::usedevents, eventqacollection::x_DA, eventqacollection::x_JB, eventqacollection::x_NM, eventqacollection::y_DA, eventqacollection::y_JB, and eventqacollection::y_NM.