EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_CEmc_Spacal.C File Reference
G4_CEmc_Spacal.C File Reference
#include "GlobalVariables.C"
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterPositionCorrection.h>
#include <fun4all/Fun4AllServer.h>
#include <g4detectors/PHG4CylinderCellReco.h>
#include <g4detectors/PHG4CylinderGeom_Spacalv1.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4FullProjSpacalCellReco.h>
#include <g4detectors/PHG4SpacalSubsystem.h>
#include <g4calo/RawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <iostream>
Enumerations
enum enu_Cemc_clusterizer { kCemcGraphClusterizer, kCemcTemplateClusterizer }
Functions
double CEmc_1DProjectiveSpacal (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
EMCal setup macro - 1D azimuthal projective SPACAL.
double CEmc_2DProjectiveSpacal (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
2D full projective SPACAL
void CEmcInit (const int nslats=1)
graph clusterizer, RawClusterBuilderGraph
double CEmc (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
EMCal main setup macro.
void CEMC_Cells (int verbosity=0)
void CEMC_Towers (int verbosity=0)
void CEMC_Clusters (int verbosity=0)
void CEMC_Eval (std::string outputfile, int verbosity=0)
Variables
int Min_cemc_layer = 1
int Max_cemc_layer = 1
int Cemc_spacal_configuration = PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal
enu_Cemc_clusterizer Cemc_clusterizer = kCemcTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Enumeration Type Documentation
enum enu_Cemc_clusterizer
Enumerator:
kCemcGraphClusterizer
kCemcTemplateClusterizer
Definition at line 37 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 37 of file G4_CEmc_Spacal.C
Function Documentation
double CEmc (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
EMCal main setup macro.
Definition at line 60 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 60 of file G4_CEmc_Spacal.C
References CEmc_1DProjectiveSpacal(), CEmc_2DProjectiveSpacal(), exit(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, and PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal.
double CEmc_1DProjectiveSpacal (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
EMCal setup macro - 1D azimuthal projective SPACAL.
Definition at line 85 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 85 of file G4_CEmc_Spacal.C
References cemc, exit(), Min_cemc_layer, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by CEmc().
double CEmc_2DProjectiveSpacal (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
2D full projective SPACAL
Definition at line 166 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 166 of file G4_CEmc_Spacal.C
References cemc, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_SameLengthFiberPerTower, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SetCalibrationFileDir(), PHG4DetectorSubsystem::SuperDetector(), PHG4DetectorSubsystem::UseCalibFiles(), Fun4AllBase::Verbosity(), and PHG4DetectorSubsystem::xml.
Referenced by CEmc().
void CEMC_Cells (int verbosity = 0)
Definition at line 282 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 282 of file G4_CEmc_Spacal.C
References PHG4CylinderCellReco::cellsize(), PHG4CylinderCellReco::Detector(), PHG4FullProjSpacalCellReco::Detector(), exit(), PHG4FullProjSpacalCellReco::get_light_collection_model(), Fun4AllServer::instance(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal, PHG4FullProjSpacalCellReco::LightCollectionModel::load_data_file(), Max_cemc_layer, Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
void CEMC_Clusters (int verbosity = 0)
Definition at line 404 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 404 of file G4_CEmc_Spacal.C
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), exit(), RawClusterPositionCorrection::Get_eclus_CalibrationParameters(), RawClusterPositionCorrection::Get_ecore_CalibrationParameters(), Fun4AllServer::instance(), kCemcGraphClusterizer, kCemcTemplateClusterizer, RawClusterBuilderTemplate::LoadProfile(), PHParameters::ReadFromFile(), Fun4AllServer::registerSubsystem(), RawClusterBuilderTemplate::set_threshold_energy(), and Fun4AllBase::Verbosity().
void CEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 449 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 449 of file G4_CEmc_Spacal.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
void CEMC_Towers (int verbosity = 0)
Definition at line 324 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 324 of file G4_CEmc_Spacal.C
References RawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Acts::UnitConstants::e, exit(), RawTowerCalibration::GetCalibrationParameters(), Fun4AllServer::instance(), PHG4CylinderGeom_Spacalv1::k1DProjectiveSpacal, PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal, RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitization, RawTowerCalibration::kTower_by_tower_calibration, PHParameters::ReadFromFile(), Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), and Fun4AllBase::Verbosity().
void CEmcInit (const int nslats = 1)
graph clusterizer, RawClusterBuilderGraph
Definition at line 52 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 52 of file G4_CEmc_Spacal.C
Variable Documentation
enu_Cemc_clusterizer Cemc_clusterizer = kCemcTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 45 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 45 of file G4_CEmc_Spacal.C
int Cemc_spacal_configuration = PHG4CylinderGeom_Spacalv1::k2DProjectiveSpacal
Definition at line 35 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 35 of file G4_CEmc_Spacal.C
int Max_cemc_layer = 1
Definition at line 29 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 29 of file G4_CEmc_Spacal.C
Referenced by CEMC_Cells(), and Fun4All_G4_Clusters().
int Min_cemc_layer = 1
Definition at line 28 of file G4_CEmc_Spacal.C.
View newest version in sPHENIX GitHub at line 28 of file G4_CEmc_Spacal.C
Referenced by CEmc_1DProjectiveSpacal(), and Fun4All_G4_Clusters().