EIC Software: fun4all_macros/blob/master/macros/g4simulations/G4_FHCAL.C File Reference
G4_FHCAL.C File Reference
#include "GlobalVariables.C"
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4ForwardCalCellReco.h>
#include <g4detectors/PHG4ForwardHcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4FHCAL
Functions
void FHCALInit ()
void FHCAL_Cells (int verbosity=0)
void FHCALSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void FHCAL_Towers (int verbosity=0)
void FHCAL_Clusters (int verbosity=0)
void FHCAL_Eval (std::string outputfile, int verbosity=0)
Variables
static bool Enable::FHCAL = false
const double G4FHCAL::Gz0 = 400.
const double G4FHCAL::Gdz = 100.
const double G4FHCAL::outer_radius = 262.
Function Documentation
void FHCAL_Cells (int verbosity = 0)
Definition at line 44 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 44 of file G4_FHCAL.C
References PHG4ForwardCalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_G4_EICDetector(), and Fun4All_G4_fsPHENIX().
void FHCAL_Clusters (int verbosity = 0)
Definition at line 134 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 134 of file G4_FHCAL.C
References RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), and Fun4All_G4_fsPHENIX().
void FHCAL_Eval (std::string outputfile, int verbosity = 0)
Definition at line 147 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 147 of file G4_FHCAL.C
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void FHCAL_Towers (int verbosity = 0)
Definition at line 78 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 78 of file G4_FHCAL.C
References RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), and Fun4All_G4_fsPHENIX().
void FHCALInit ()
Definition at line 38 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 38 of file G4_FHCAL.C
References G4FHCAL::Gdz, G4FHCAL::Gz0, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, and G4FHCAL::outer_radius.
Referenced by G4Init().
void FHCALSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated FHCAL module
Definition at line 55 of file G4_FHCAL.C.
View newest version in sPHENIX GitHub at line 55 of file G4_FHCAL.C
References Fun4AllServer::instance(), overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4ForwardHcalSubsystem::SetAbsorberActive(), and PHG4ForwardHcalSubsystem::SetTowerMappingFile().
Referenced by G4Setup().