EIC Software: TpcSpaceChargeReconstruction Class Reference
TpcSpaceChargeReconstruction Class Reference
performs space charge distortion reconstruction using tracks To reconstruct the distortions dr0, drphi0 and dz0 in a given volume element, the following chisquare is minimized chisquare = sum_cluster (drphi - (drphi0 + dr0 tan alpha))**2/error**2 + sum_cluster (dz - (dz0 + dr0 tan beta))**2/error**2 with
#include <fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstruction.h>
Public Member Functions
TpcSpaceChargeReconstruction (const std::string &="TPCSPACECHARGERECONSTRUCTION")
constructor
virtual int Init (PHCompositeNode *)
global initialization
virtual int InitRun (PHCompositeNode *)
run initialization
virtual int process_event (PHCompositeNode *)
event processing
virtual int End (PHCompositeNode *)
end of processing
configuration
void set_tpc_layers (unsigned int first_layer, unsigned int n_layers)
set tpc layers
void set_grid_dimensions (int zbins, int rbins, int phibins)
set grid dimensions
void set_outputfile (const std::string &filename)
output file
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
using matrix_t = Eigen::Matrix< float, m_ncoord, m_ncoord >
using column_t = Eigen::Matrix< float, m_ncoord, 1 >
Private Member Functions
int load_nodes (PHCompositeNode *)
load nodes
void process_tracks ()
process tracks
void process_track (SvtxTrack *)
process track
void calculate_distortions (PHCompositeNode *)
calculate distortions
int get_cell (int iz, int ir, int iphi) const
get cell from z, r and phi index
int get_cell (TrkrDefs::cluskey, TrkrCluster *) const
get relevant cell for a given cluster
Private Attributes
std::string m_outputfile = "TpcSpaceChargeReconstruction.root"
output file
unsigned int m_firstlayer_tpc = 7
unsigned int m_nlayers_tpc = 48
std::vector< matrix_t > m_lhs
left hand side matrices for distortion inversions
std::vector< column_t > m_rhs
right hand side matrices for distortion inversions
std::vector< int > m_cluster_count
keep track of how many clusters are used per cell
grid size
int m_zbins = 50
int m_phibins = 72
int m_rbins = 48
int m_totalbins = m_zbins*m_phibins*m_rbins
nodes
SvtxTrackMap * m_track_map = nullptr
TrkrClusterContainer * m_cluster_map = nullptr
Static Private Attributes
static constexpr int m_ncoord = 3
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
performs space charge distortion reconstruction using tracks To reconstruct the distortions dr0, drphi0 and dz0 in a given volume element, the following chisquare is minimized chisquare = sum_cluster (drphi - (drphi0 + dr0 tan alpha))**2/error**2 + sum_cluster (dz - (dz0 + dr0 tan beta))**2/error**2 with
drphi and dz the residuals (track - cluster) measured for a given cluster
alpha and beta the track angles at the cluster in the rphi,r plane and the z,r plane, respectively The chisquare being quadratic in dr0, drphi0 and dz0, it can be minimized analytically. This results in a linear equation lhs[i].[corrections] = rhs[i], and thus [corrections] = lhs[i]**(-1).rhs[i] The lhs and rhs matrices are filled in TpcSpaceChargeReconstruction::process_track The inversion is performed in TpcSpaceChargeReconstruction::calculate_distortions
Definition at line 36 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 36 of file TpcSpaceChargeReconstruction.h
Member Typedef Documentation
using TpcSpaceChargeReconstruction::column_t = Eigen::Matrix<float, m_ncoord, 1 > private
Definition at line 118 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 118 of file TpcSpaceChargeReconstruction.h
using TpcSpaceChargeReconstruction::matrix_t = Eigen::Matrix<float, m_ncoord, m_ncoord > private
Definition at line 117 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 117 of file TpcSpaceChargeReconstruction.h
Constructor & Destructor Documentation
TpcSpaceChargeReconstruction::TpcSpaceChargeReconstruction (const std::string & name = "TPCSPACECHARGERECONSTRUCTION")
constructor
Definition at line 39 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 39 of file TpcSpaceChargeReconstruction.cc
Member Function Documentation
void TpcSpaceChargeReconstruction::calculate_distortions (PHCompositeNode * topNode) private
calculate distortions
Definition at line 251 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 251 of file TpcSpaceChargeReconstruction.cc
References Acts::Test::delta, get_cell(), inner_radius, m_firstlayer_tpc, m_lhs, m_ncoord, m_nlayers_tpc, m_outputfile, m_phibins, m_rbins, m_rhs, m_totalbins, m_zbins, G4FEMC::outer_radius, PHWHERE, r, and value.
Referenced by End().
int TpcSpaceChargeReconstruction::End (PHCompositeNode * topNode) virtual
end of processing
Reimplemented from SubsysReco.
Definition at line 92 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 92 of file TpcSpaceChargeReconstruction.cc
References calculate_distortions(), and Fun4AllReturnCodes::EVENT_OK.
int TpcSpaceChargeReconstruction::get_cell (int iz, int ir, int iphi) const private
get cell from z, r and phi index
Definition at line 312 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 312 of file TpcSpaceChargeReconstruction.cc
References m_phibins, m_rbins, and m_zbins.
Referenced by calculate_distortions(), get_cell(), and process_track().
int TpcSpaceChargeReconstruction::get_cell (TrkrDefs::cluskey cluster_key, TrkrCluster * cluster) const private
get relevant cell for a given cluster
Definition at line 321 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 321 of file TpcSpaceChargeReconstruction.cc
References get_cell(), TrkrDefs::getLayer(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), m_firstlayer_tpc, m_nlayers_tpc, m_phibins, M_PI, m_rbins, and m_zbins.
int TpcSpaceChargeReconstruction::Init (PHCompositeNode * topNode) virtual
global initialization
Reimplemented from SubsysReco.
Definition at line 64 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 64 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, m_cluster_count, m_lhs, m_rhs, and m_totalbins.
int TpcSpaceChargeReconstruction::InitRun (PHCompositeNode *) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 76 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 76 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK.
int TpcSpaceChargeReconstruction::load_nodes (PHCompositeNode * topNode) private
load nodes
Definition at line 99 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 99 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, m_cluster_map, and m_track_map.
Referenced by process_event().
int TpcSpaceChargeReconstruction::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 80 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 80 of file TpcSpaceChargeReconstruction.cc
References Fun4AllReturnCodes::EVENT_OK, load_nodes(), and process_tracks().
void TpcSpaceChargeReconstruction::process_track (SvtxTrack * track) private
process track
Definition at line 117 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 117 of file TpcSpaceChargeReconstruction.cc
References kdfinder::abs(), SvtxTrack::begin_cluster_keys(), SvtxTrack::begin_states(), cos(), QAG4Util::delta_phi(), G4HCALIN::dz, SvtxTrack::end_cluster_keys(), SvtxTrack::end_states(), TrkrClusterContainer::findCluster(), get_cell(), QAG4Util::get_r(), TrkrDefs::getLayer(), m_cluster_count, m_cluster_map, m_firstlayer_tpc, m_lhs, m_nlayers_tpc, m_rhs, m_totalbins, PHWHERE, and square().
Referenced by process_tracks().
void TpcSpaceChargeReconstruction::process_tracks () private
process tracks
Definition at line 108 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 108 of file TpcSpaceChargeReconstruction.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), m_cluster_map, m_track_map, and process_track().
Referenced by process_event().
void TpcSpaceChargeReconstruction::set_grid_dimensions (int zbins, int rbins, int phibins)
set grid dimensions
Parameters
zbins the number of bins along z
rbins the number of bins in the radial direction. It must be a divider of the number of tpc layers (by default 48), e.g. 1, 12, 24, 48
phibins the number of bins in the azimuth direction
Definition at line 51 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 51 of file TpcSpaceChargeReconstruction.cc
References m_phibins, m_rbins, m_totalbins, m_zbins, and phibins.
void TpcSpaceChargeReconstruction::set_outputfile (const std::string & filename)
output file
for now only TGraphs of space charge corrections vs r are stored ultimately one wants to save the data in a format that is suitable for use in the reconstruction
Definition at line 60 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 60 of file TpcSpaceChargeReconstruction.cc
References m_outputfile.
void TpcSpaceChargeReconstruction::set_tpc_layers (unsigned int first_layer, unsigned int n_layers)
set tpc layers
Definition at line 44 of file TpcSpaceChargeReconstruction.cc.
View newest version in sPHENIX GitHub at line 44 of file TpcSpaceChargeReconstruction.cc
References m_firstlayer_tpc, and m_nlayers_tpc.
Member Data Documentation
std::vector<int> TpcSpaceChargeReconstruction::m_cluster_count private
keep track of how many clusters are used per cell
Definition at line 127 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 127 of file TpcSpaceChargeReconstruction.h
Referenced by Init(), and process_track().
TrkrClusterContainer* TpcSpaceChargeReconstruction::m_cluster_map = nullptr private
Definition at line 132 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 132 of file TpcSpaceChargeReconstruction.h
Referenced by load_nodes(), process_track(), and process_tracks().
unsigned int TpcSpaceChargeReconstruction::m_firstlayer_tpc = 7 private
Definition at line 104 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 104 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), process_track(), and set_tpc_layers().
std::vector<matrix_t> TpcSpaceChargeReconstruction::m_lhs private
left hand side matrices for distortion inversions
Definition at line 121 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 121 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), Init(), and process_track().
constexpr int TpcSpaceChargeReconstruction::m_ncoord = 3 static private
Definition at line 116 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 116 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions().
unsigned int TpcSpaceChargeReconstruction::m_nlayers_tpc = 48 private
Definition at line 105 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 105 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), process_track(), and set_tpc_layers().
std::string TpcSpaceChargeReconstruction::m_outputfile = "TpcSpaceChargeReconstruction.root" private
output file
Definition at line 101 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 101 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), and set_outputfile().
int TpcSpaceChargeReconstruction::m_phibins = 72 private
Definition at line 110 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 110 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), and set_grid_dimensions().
int TpcSpaceChargeReconstruction::m_rbins = 48 private
Definition at line 111 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 111 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), and set_grid_dimensions().
std::vector<column_t> TpcSpaceChargeReconstruction::m_rhs private
right hand side matrices for distortion inversions
Definition at line 124 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 124 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), Init(), and process_track().
int TpcSpaceChargeReconstruction::m_totalbins = m_zbins*m_phibins*m_rbins private
Definition at line 112 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 112 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), Init(), process_track(), and set_grid_dimensions().
SvtxTrackMap* TpcSpaceChargeReconstruction::m_track_map = nullptr private
Definition at line 131 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 131 of file TpcSpaceChargeReconstruction.h
Referenced by load_nodes(), and process_tracks().
int TpcSpaceChargeReconstruction::m_zbins = 50 private
Definition at line 109 of file TpcSpaceChargeReconstruction.h.
View newest version in sPHENIX GitHub at line 109 of file TpcSpaceChargeReconstruction.h
Referenced by calculate_distortions(), get_cell(), and set_grid_dimensions().
The documentation for this class was generated from the following files:
fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
fun4all_coresoftware/blob/master/offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc